### ISSUE TITLE
D3.js w wizualizacji danych

### ISSUE THREAD

**Issue by erykpiast** [meetjspl/poznan#1]
Chciałbym opowiedzieć o zastosowaniach [D3.js](http://d3js.org/) w wizualizacji danych, podstawowych konceptach tej biblioteki, wadach i zaletach (hard part) i potencjalnych problemach, które mogą dotknąć początkujących. Prezentacja raczej w stylu overview, nie użytkowników tej biblioteki żądnych specjalistycznej widzy, raczej dla tych, którzy chcą zobaczyć, z czym to się je.

**Comment by naugtur** [comment]
Brzmi dobrze!
Jeśli to się zmieści w czasie prelekcji, chętnie zobaczę jak się zabrać do pisania swojego layoutu zamiast używania jednego z domyślnych. Ale zdaję sobie sprawę, że to może być za dużo na jedną preskę.

**Comment by boulderdash-** [comment]
Przykładałem się jakiś czas temu do spróbowania się z D3 ale brakowało mi jakiegoś dobrego wstępu więc bardzo chętnie go zobaczę :+1:

**Comment by vonsko** [comment]
swoje katusze już przebyłem - chętnie posłucham np o różnych layoutach i o specyficznych zastosowaniach

**Comment by IgnetStudio** [comment]
chciałbym, żebyś opisał pokrótce możliwości fajnych dodatków do D3. mam na myśli: NVD3, c3, DC.JS, TauCharts, addepar, protovis, xCharts, Vida, Unveil.js, d3-geo-projection, n3, PykCharts.js, venn.js :)

**Comment by erykpiast** [comment]
@IgnetStudio, żadnej z tych rzeczy nie używałem, więc nie zrobię tego na fachowym poziomie. Ale spojrzę przynajmniej i wylistuję, dzięki za listę :D

**Comment by naugtur** [comment]
Dzięki za prezentację. Daj link do slajdów ;)

**Comment by erykpiast** [comment]
Proszę! https://slides.com/erykpiast/d3

**Comment by SebastianPozoga** [comment]
Prezentacja dostępna na:
http://events.pozoga.eu/meet-js-poznan-10-2015/
