### ISSUE TITLE
Reactive functional frontend

### ISSUE THREAD

**Issue by sihingkk** [meetjspl/poznan#10]
Będzie o tym skąd się wzieło i jak to się stało, że koncepty ze smalltaka przeżywają teraz renesans.
Usecase na przykładzie Allegro i ClojureScript (z krótkim wprowadzeniem do niego).
Rationale, dlaczego warto pisać tak a nie inaczej.

**Comment by erykpiast** [comment]
Łał!

**Comment by naugtur** [comment]
Temat na czasie.

Proponuję termin pod koniec lipca, pasowałby?
Szczegóły dogadamy przez maila.

**Comment by sihingkk** [comment]
pewnie =)

**Comment by sihingkk** [comment]
rzeczy o których fajnie byłoby wspomnieć (będzie się dynamicznie zmieniać, ale sugestie są mile widziane)
- clojurescript, reagent i re-frame
- co to functional
- co to reactive
- co to functional reactive ;)
- bardzo krótko o tym co wspólnego mają ze sobą Flux, Pedestal App, Hoplon, OM, Elm
- graf sygnałów, eventy, routing i skończona maszyna stanów
- baza danych jako stream
- zalety i wady, na co trzeba uważać, kiedy się przydaje
- testowalność
- adopcja

**Comment by erykpiast** [comment]
Jeżeli mowa o apkach uruchamianych w przeglądarce/na node - współpraca z
resztą świata, tj. zewnętrznymi libami. Mógłbyś zahaczyć o ten temat?

pon., 4.07.2016 o 22:41 użytkownik Krzysztof Kaczmarek <
notifications@github.com> napisał:

**Comment by naugtur** [comment]
Mnie zawsze interesuje jedna rzecz - narzędzia do debugowania. Bo zwykły debugger przy reaktywnym kodzie jest mało pomocny.

**Comment by adrianmroz** [comment]
> clojurescript, reagent i re-frame
> graf sygnałów, eventy, routing i skończona maszyna stanów

re-frame i te aspekty brzmią jak bardzo dużo contentu

Skoro chcesz omówić bazę danych jako stream i reagenta to polecam `mpdairy/posh` i ogólnie uważam, że `derived data` to najprzyjemniejsze spojrzenie na frp :)

**Comment by naugtur** [comment]
Jeśli treści jest dużo, możemy zrobić prelekcję 20min i warsztat dla małej grupy później.

**Comment by sihingkk** [comment]
hej, 

dzięki bardzo za sugestie =)

debugowanie - wdzięczny temat, szczególnie w świecie przeglądarkowym (z nodem mam mało doświadczeń produkcyjnych)

@erykpiast - coś szczególnego chodzi Ci po głowie?

zróbmy prelekcję, spróbuję wyciąć tak żeby było mięsko, ale żeby jednocześnie nie zanudzić.

z warsztatami jest odrobinę problem - koszt wejścia to poznanie clojure/clojurescript, ale jak będą chętni to możemy coś zrobić.

Planuje w na jesień puścić otwarte warcztaty clj(s) - możemy to spróbować jakoś metnalnie złączyć

**Comment by adrianmroz** [comment]
Jeśli chodzi o clojure to ja bardzo chętnie pomogę, może zorganizujemy coś bardziej tematycznego? 

@naugtur: jakieś pomysły organizacyjne?

**Comment by naugtur** [comment]
Załatwienie miejsca na warsztaty i ewentualnego sponsora pikuś. Tylko proponuję ruszać z takimi rzeczami po wakacjach.
Zapisy też ogarniemy w ramach meet.js

**Comment by erykpiast** [comment]
Podczepiam się z tym, co pokazywałem na Open Mic: https://github.com/clojure-cookbook/clojure-cookbook.

Czekam na slajdy! :) Tak w ogóle, świetna prezentacja! Tak udanego meet.js-a już dawno nie mieliśmy.

**Comment by SebastianPozoga** [comment]
Nagrania już dostępne na:
http://events.pozoga.eu/meet-js-sierpien-2016/

**Comment by erykpiast** [comment]
@sihingkk, co ze slajdami? chciałbym zamknąć issue.
