### ISSUE TITLE
Polish - English

### ISSUE THREAD

**Issue by ozhanefemeral** [meetjspl/poznan#106]
Hej! This is Ozzy, and I would like to attend Meet.js#56 next Tuesday. 

However I don't speak Polish very well, and I assume the whole meeting/talk is in Polish. If Polish, I may have difficulty following along and don't think my attendance will be worthwhile. Will the event be conducted in English?

Cheers!

**Comment by naugtur** [comment]
It's a secret but I'll tell you. The purpose of these events is networking. Talks are there mostly to lure people in 😉

I'll let the current organizers answer your actual question 😅

**Comment by SebastianPozoga** [comment]
I asked the speakers about presenting in English. Speakers choose the presentation language themselves, but Polish is not the only language. I encourage you to submit a presentation :-) We will be happy to develop our community.

**Comment by ozhanefemeral** [comment]
> It's a secret but I'll tell you. The purpose of these events is networking. Talks are there mostly to lure people in 😉
> 
> I'll let the current organizers answer your actual question 😅

Hahahhaha nice knowing that! That sounds awesome, lets see if I can blend in!

> I asked the speakers about presenting in English. Speakers choose the presentation language themselves, but Polish is not the only language. I encourage you to submit a presentation :-) We will be happy to develop our community.

Thank you so much for taking this initiative! Also I appreciate your encouragement, but I am not well prepared for a presentation :)

**Comment by SebastianPozoga** [comment]
@ozhanefemeral [Radosław Karbowiak](https://github.com/rkarbowiak) agreed to conduct the presentation in English :-) 
Well you will hear about "Practical Guide: Implementing LLM Driven Features in Your System"
Join us and enjoy it :-)

**Comment by SebastianPozoga** [comment]
it was nice to see you :-)
