### ISSUE TITLE
Universal JavaScript with React

### ISSUE THREAD

**Issue by wojciech-panek** [meetjspl/poznan#11]
Dzięki za możliwość zaprezentowania się. Poniżej znajduje się prezentacja.

[Link](https://docs.google.com/presentation/d/1WycksGHIsEUXZj3zWv8lIlXYZFIuL9KsdwI3QUAUIuA/edit?usp=sharing)

**Comment by naugtur** [comment]
Dzięki! Jest link, zamykam :)

**Comment by SebastianPozoga** [comment]
Prezentacja dostępna na:
http://events.pozoga.eu/meet-js-poznan-czerwiec-2016/
