### ISSUE TITLE
Prototypowanie z Emberem

### ISSUE THREAD

**Issue by hakubo** [meetjspl/poznan#12]
Mały live coding (albo copy coding) o tym jak można szybko i przyjemnie prototypować aplikacje w [Emberze](http://emberjs.com). Stworzyć model, proste view, jak czas pozwoli to jak dodać animacje oraz renderowanie po stronie serwera.

**Comment by naugtur** [comment]
Jaka wersja Embera? 
Z virtual dom i immutable, czy jeszcze bez?

Przydałoby się trochę wprowadzenia o tm czym Ember jest, czym się wyróżnia, o tym, że utrzymuje ścieżkę migracji na nowsze technologie, które wprowadza itp.

**Comment by webmajstr** [comment]
Jak dla mnie temat super, ale dołączam się do prośby @naugtur , żeby prezentacja miała jakiś ogólnikowy wstęp do Embera. Wtedy z automatu osoby niewtajemniczone będą miały okazję lepiej zrozumieć dalszą część dotyczącą prototypowania.

**Comment by hakubo** [comment]
Ember 2.6.1

Myślę, że małe info o Ember uda mi się tam wślizgnąć. Dzięki!

**Comment by hakubo** [comment]
@naugtur na jaki język powinienem się nastawić? PL czy EN?

**Comment by naugtur** [comment]
mówisz PL, materiały dowolnie

**Comment by naugtur** [comment]
link do preski i zamykam.

**Comment by SebastianPozoga** [comment]
Nagrania już dostępne na:
http://events.pozoga.eu/meet-js-sierpien-2016/

**Comment by erykpiast** [comment]
@hakubo, czekamy na slajdy :)

**Comment by hakubo** [comment]
omg omg omg, wybaczcie, zupełnie zapomniałem.
Prezentacja jest tu: https://docs.google.com/presentation/d/1wpgolxSt1uX6bVvmo1_94Gn-38Qwltxf7tv3HfmrS5I/edit?usp=sharing

**Comment by erykpiast** [comment]
Super, dzięki! :dancer:
