### ISSUE TITLE
In npm we trust

### ISSUE THREAD

**Issue by naugtur** [meetjspl/poznan#13]
Historia left-pad i jej konsekwencje, jak zrobić wirusa rozprzestrzeniającego się po npm-ie, i przede wszystkim - prezentacja nowego narzędzia, które napisałem w ostatni piątek, żeby się przed tym w końcu zabezpieczyć. :)

**Comment by naugtur** [comment]
preska http://naugtur.pl/pres3/npmsec

**Comment by SebastianPozoga** [comment]
Nagrania już dostępne na:
http://events.pozoga.eu/meet-js-sierpien-2016/
