### ISSUE TITLE
git rebase i kilka innych sztuczek

### ISSUE THREAD

**Issue by erykpiast** [meetjspl/poznan#14]
Nie jest to zupełnie temat związany z JS-em, ale potrzebny, myślę. Z gita korzysta na co dzień każdy, ale niewiele osób, tak mi się zdaje, używa czegoś poza `commit`, `pull` i `push`. Nie chcę opowiadać o gitflow, strategii zarządzania repozytoriami czy działaniu gita pod maską, raczej przedstawić polecenia, które są w stanie ułatwić pracę z repozytorium (zminimalizować prawdopodobieństwo wystąpienia momentów "WTF, jak to cofnąć?!") i zrozumieć, co tak naprawdę dzieje się. Proszę o łapki w górę, jeśli jesteście zainteresowani tematem.

**Comment by ferrante** [comment]
Bardzo potrzebny talk w community imho. :)

**Comment by bigsergey** [comment]
Temat super!

**Comment by przemyslawjanpietrzak** [comment]
Słuchałbym!

**Comment by naugtur** [comment]
Dodałbym coś o analizowaniu drzewa, gitk, jak w ogóle wyświetlić je w terminalu.
Żeby ze zrozumieniem grzebać w historii, trzeba najpierw ją zobaczyć ;)

**Comment by bigsergey** [comment]
Można też wspomnieć o https://github.com/jakubnabrdalik/gitkurwa i innych podobnych repo zawierających przydatne aliasy.
