### ISSUE TITLE
beyond npm install

### ISSUE THREAD

**Issue by erykpiast** [meetjspl/poznan#15]
NPM to narzędzie dużo potężniejsze i ma trochę więcej poleceń niż `install`. To wszystko co poza nie przydaje się wbrew pozorom tylko osobom releasującym własne moduły na npmjs.org. Prywatne paczki hostowane w wewnętrznych repozytoriach mogą usprawnić zarządzanie kodem w firmie, szczególnie przy wielu projektach. Chciałbym opowiedzieć o skryptach, cyklu życia paczki, poleceniach ułatwiających releasowanie wersji oraz pokazać przepis na efektywne zarządzanie paczką.

Jeżeli macie jakieś pomysły, o czym warto powiedzieć w tym temacie, śmiało.

**Comment by adrianmroz** [comment]
`npm link`!

**Comment by bigsergey** [comment]
Nice one!

**Comment by naugtur** [comment]
Ale obiecaj, że powiesz o npm preversion i npm postversion

**Comment by erykpiast** [comment]
@naugtur, you bet!

**Comment by naugtur** [comment]
Dodałem Ci spowrotem labelkę, bo to najlepiej będzie zrobić w formie prezentacji.

**Comment by Suiseki** [comment]
Ja w kontekście skryptów npm chętnie  bym usłyszał o różnych odmianach npm watch. Trochę nie rozumiem o co chodzi z tą mnogością tworów. Zamiast jednego globalnego watch do wszystkiego, to mamy watch, npm-watch, babel-watch, watch-uglify, nodemon i gdy przy tym całym „bogactwie” klonów chcę zrobić watch żeby po zmianie jednego pliku odpalał się inny skrypt to jakoś nie mogę przebrnąć.

**Comment by erykpiast** [comment]
@Suiseki szczerze mówiąc nie mam z tym większego doświadczenia. Nodemon + opcja `--watch` w poszczególnych toolach do tej pory mi wystarczała :)

**Comment by Suiseki** [comment]
Ale czy nodemon nie służy do restartowania serwera (nie korzystałem, tylko czytałem o tym)? Nie zależy mi (co prawda nie też nie bardzo przeszkadza), żeby po każdym odpaleniu babela czy kompilacji sassa restartował mi się node. Nie spowalnia to wszystkiego?

**Comment by erykpiast** [comment]
Mmm, nie bardzo rozumiem, czego konretnie potrzebujesz. Programujesz dla node z Babelem i chcesz mieć skrypt, który będzie transpilował Twój kod na bieżąco i podmieniał go w działającej apce?

**Comment by Suiseki** [comment]
Tak, zapis pliku js pisanego w ES6 odpala (watch pliku A) babel, który tworzy mi przetranspilowany plik. Tutaj zapis również miałby być obserwowany (watch pliku B) i odpalić uglify. Wiem, że to nie jest optymalny proces, bo tak na prawdę na etapie developmentu nie jest mi konieczny zminifikowany plik. Mógłbym sobie go ręcznie odpalić przed wypuszczeniem kodu na produkcję, Chciałbym jednak wiedzieć jak, w razie potrzeby mogę łączyć procesy w skryptach, tak że koniec jednego procesu (np zapis) odpala następny.

**Comment by erykpiast** [comment]
Okej, teraz rozumiem! Ale przyznam, że jest to usecase, nad którym musiałbym się zastanowić. Bez pośrednich plików (na przykład niezminifikowane ES5) to będzie trudne... Pomyślę!
