### ISSUE TITLE
[follow up] datascript, reagent, posh

### ISSUE THREAD

**Issue by adrianmroz** [meetjspl/poznan#16]
Była prezentacja o datascripcie i reagencie - chciałbym pokazać jak te dwa rozwiązania do siebie pasują. 
Jak reaktywnie połączyć reagenta z bazą danych. Jak generować zapytania dla drzewa komponentów. Jak reagować na zmiany stanu i integrować to z obcym kodem. 
Chcę pokazać dużo przykładów (non-live coding) i opowiedzieć dlaczego lisp way is the way (jak najbardziej konkretnie, głównie o tym co daje nam wyrażenie wszystkiego jako podstawowe struktury danych). 

Wszystko przy założeniu, że mogę pokazać kod w clojure. 

Jestem otwarty na formę.

**Comment by naugtur** [comment]
To pomyślmy jak to zrobić, żeby ludzie nie wymiękli ;)
Nie może być zbyt abstrakcyjnie.

**Comment by erykpiast** [comment]
A masz pomysł na jakim usecase to pokazać? TODO list czy coś innego?

**Comment by adrianmroz** [comment]
Myślałem o osobnych, prostszych case'ach. 
Jakiś counter i ewentualnie multi-counter to zaprezentowania jak się robi w tym odpowiednik reduxowego hello world. I pokazać wtedy różnice.
Jakieś drzewo komponentów - listę itemów z poditemami - na składanie zapytań.
Ze streamami jeszcze nie wiem. Coś w stylu zewnętrzne api do trackowania albo A/B.

**Comment by naugtur** [comment]
Zestawienie z reduxem byłoby niezłe. Na jakimś życiowym przykładzie.

Jako heurystykę przy planowaniu prezentacji polecam "Jak wytłumaczyłbyś to programiście, który do tej pory tylko uzupełniał widoki w dużym projekcie"

**Comment by adrianmroz** [comment]
Zakładałbym chociaż wiedzę z prezentacji @sihingkk. Jeśli się mylę, to moze jednak warsztaty?

**Comment by sihingkk** [comment]
zróbmy może najpierw warszataty - mam bardzo negatywne doświadczenia z pokazywania kodu clojure ludziom którzy nie dotykali nigdy nic Lisp'owego.

założę może wątek pod warsztaty? alternatywnie można by zachęcic do spędzenia 2h na http://4clojure.com ale to ma nikłe szanse powodzenia

**Comment by naugtur** [comment]
@adrianmroz bez odrobiny cynizmu powiem, że się mylisz. 
Uczestnicy musieliby mieć wcześniejsze doświadczenia z clojure żeby zapamiętać więcej niż 50% prezentacji @sihingkk - obstawiam, że większość z nich zapamiętała głównie "fajne to clojure, trzeba by spróbować" i odrobinę składni. 
I tak to działa, że sukcesem prezentacji jest inspirowanie lub uświadamianie o istnieniu pewnych rozwiązań.

**Comment by adrianmroz** [comment]
@sihingkk @naugtur 

Jeśli warsztaty to jakby to wyglądało? Fajnie by było gdyby były różne segmenty, więc pewnie ktoś jeszcze by musiał dołączyć z clojure'owym tematem?

**Comment by naugtur** [comment]
Generalnie nie ma problemu z zorganizowaniem jednego warsztatu z zapisami. Trzeba to tylko zaplanować. 
Ale z mojej strony polecam przygotowanie warsztatu we dwóch. Super sprawa móc z kimś współpracować przy przygotowaniach.

**Comment by sihingkk** [comment]
chętnie pomogę przy warsztatach, przeszkoliłem ponad 50 osób z clj, więc wiem przynajmniej jak tego nie robić ;)

**Comment by sihingkk** [comment]
może zacznijmy od końca, (jezeli chodzi o warsztaty ;) )
ustawmy sobie deadline na poczatek grudnia
kto się pisze żeby je spróbować przeprowadzić?

jak już będziemy wiedzieć - spotkajmy się i zreverseinżynierujmy co trzeba zrobić

to kto by chciał? :)

**Comment by naugtur** [comment]
Na początku grudnia będę w trasie, ale od 9 powinienem być na miejscu i mogę pomóc organizować (lokalizację, sponsora etc.)

Mogę też pomóc z dopracowaniem samej formy. 

Spotkajmy się jakoś w tym tygodniu

**Comment by adrianmroz** [comment]
Może po meetjs w środę? Ja jestem w każdym razie chętny. Mam jakiś pomysł, ale wolałbym zderzyć go z doświadczeniem @sihingkk najpierw :)

**Comment by naugtur** [comment]
@adrianmroz Może być po Meet.js w czwartek, bo jeśli jest jakiś w środę to chyba ktoś inny go organizuje :p 
I tak chciałem iść z kimś na piwo po meecie, więc ja bym się pisał

**Comment by adrianmroz** [comment]
Owszem, czwartek :)

W dniu 10 października 2016 20:20 użytkownik Zbyszek Tenerowicz <
notifications@github.com> napisał:

**Comment by sihingkk** [comment]
@adrianmroz napisz proszę do mnie maila krzysztof.kaczmarek@me.com albo przedzwoń proszę, 721 250 999

**Comment by sihingkk** [comment]
A jeżeli chodzi o warsztaty - proponuje połowe stycznia.

pytanie co byśmy chcieli? możemy zrobić coś w stylu tego jak Ryan Florence robi szkolenia z React'a.
 - podstawy clojure
 -  reagent, pokazać jak robić pure components
 - dołożyć datascript
i sklecić z tego jakąś niestrywialną apke - co sądzicie?

**Comment by sihingkk** [comment]
ping ;)

**Comment by erykpiast** [comment]
@adrianmroz @sihingkk @naugtur chcemy coś robić w tym temacie, czy zamykamy issue?

**Comment by naugtur** [comment]
No ja nie zrobię :p
Chłopaki się jeszcze nie dogadali.
Z Adrianem rozmawialiśmy o zorganizowaniu tego tak, żeby poprowadził w pojedynkę, ale się rozmyślił. Chyba...

**Comment by adrianmroz** [comment]
Jak widać nie potrafię się zorganizować, więc proponuję zamknąć.

**Comment by naugtur** [comment]
Jakby chęci wróciły to reopen
