### ISSUE TITLE
[cassandra][nodejs] Handling terabytes of data in Node.js

### ISSUE THREAD

**Issue by ssuperczynski** [meetjspl/poznan#18]
Hej,
przygotowuje prezentację pod kilka konferencji jak prawidłowo używać Cassandry w projektach gdzie operuje się na terabajtach danych. 
Nada się taki temat w połączeniu z Nodem?

**Comment by tniezurawski** [comment]
Brzmi interesująco! Jeśli temat nie zostanie zaakceptowany na meetjs to na jakiej konferencji można usłyszeć twoją prezentację?

**Comment by erykpiast** [comment]
Mmm, ale masz plan żeby pokazać użycie Cassandry w node tylko teoretycznie, na potrzeby prezentacji, czy używasz gdzieś takiego stacka?

**Comment by ssuperczynski** [comment]
Stack jest w użyciu, w obecnym projekcie z node.js, w 2 poprzednich w Play Framework w Scali i Apache Spark. Pokazanych będzie 6 opcji jak obrabiać dane z Cassandry, przy użyciu: 1. alasql, 2. ElasticSearcha 3. Solr 4. Apache Spark 5. Kafka 6. Cassandra UDF i UDA

**Comment by erykpiast** [comment]
Łał, dużo. Mimo wszystko mnie osobiście bardziej by interesowało dlaczego node, co poszło źle, co dobrze, takie wiesz, case study dla połączenia Cassandra + Node :)

**Comment by ssuperczynski** [comment]
Tak, taki jest zamysł. Przygotuję prezentację i załącze tu, wspólnie ocenimy czy wszystko jest ok. Jeżeli się przyjmie, chętnie bym pojeździł po innych meetupach

**Comment by naugtur** [comment]
Dasz radę to zmieścić w 20-25 minut, czy chcesz żebyśmy Ci pomogli wybrać co zostawić a czego nie?

**Comment by naugtur** [comment]
@tniezurawski my nie odrzucamy tematów, tylko pomagamy je dopracować :)

**Comment by erykpiast** [comment]
@ssuperczynski Hej, jest szansa na reaktywację tematu?

**Comment by erykpiast** [comment]
Okej, nie ma odpowiedzi więc zamykam.

**Comment by naugtur** [comment]
:( a wyglądało fajnie

@ssuperczynski zrób reopen jak zauważysz
