### ISSUE TITLE
Angular 2 / Typescript - advanced solutions

### ISSUE THREAD

**Issue by witgithub** [meetjspl/poznan#19]
Angular 2 powoli wkracza w taką fazę, że może było by warto usłyszeć coś więcej!:)

**Comment by erykpiast** [comment]
A masz jakiś konkretny plan na prezentację? Overview ficzerów, jakiś ~~oszukany~~ moderowany live coding?

**Comment by naugtur** [comment]
live coding musi być oszukany. 
Zgadzam się, że trzeba coś o tym w końcu powiedzieć. Powiedz coś więcej jak będziesz miał czas. Skąd masz wiedzę o Angularze2 ? (Jeśli nie masz i chcesz zrobić preskę po to, żeby poznać - to też cool)

**Comment by Choniawko** [comment]
Widzę że temat trochę ostygł. Ja pracuje pracuje w Angular2 od stycznia czyli praktycznie od pierwszej bety i w sumie mógłbym coś powiedzieć o swoich przemyśleniach z tym frameworkiem i trochę o nowościach i zmianach w aktualnej wersji

**Comment by naugtur** [comment]
Moim zdaniem spoko sprawa. 
Żeby nie mieszać proponuję, żebyś założył nowy issue a ten odgrzejemy albo zamkniemy. 
Chętnie się dowiem co się zmieniło. Zwłaszcza, że właśnie wyszedł "final"

**Comment by erykpiast** [comment]
@witgithub issue ma już pół roku, czy uważasz, że temat jest aktualny? chcesz zrobić prezentację?

**Comment by erykpiast** [comment]
Zamykam, brak odzewu.
