### ISSUE TITLE
Wprowadzenie do Meteora

### ISSUE THREAD

**Issue by khronedev** [meetjspl/poznan#2]
Chciałbym zrobić dużo live coding'u - z podstaw Meteora - gdzie przedstawię jak szybko można stworzyć działającą aplikację używając tej technologii. Kodowanie połączone z tłumaczeniem do czego się ten framework nie nadaje, a co robi bardzo dobrze.

**Comment by erykpiast** [comment]
ta druga część - :+1:

**Comment by naugtur** [comment]
Mieliśmy już jedną prezentację o Meteorze, ale tego do czego się nie nadaje na niej nie było :)
Livecoding mile widziany!

**Comment by naugtur** [comment]
podlinkuj tu prezentację i zamykam issue

**Comment by SebastianPozoga** [comment]
Prezentacja dostępna na:
http://events.pozoga.eu/meet-js-marzec-2016/
