### ISSUE TITLE
BackstopJS

### ISSUE THREAD

**Issue by mattrojecki** [meetjspl/poznan#20]
Prelekcja na temat tego, jak zrobić własnego bota na FB przy użyciu JS

EDIT:
Temat prezentacji zmieniony na "Testowanie regresji z użyciem BackstopJS"

**Comment by naugtur** [comment]
Brzmi dobrze.

W jakich proporcjach planujesz rozłożyć czas prezentacji pomiędzy FB i messenger a pisanie botów w JS (przetwarzanie języka etc.)?
Prezentacje zwykle planujemy na 20-25 minut.

**Comment by MateuszRojecki** [comment]
25% - 30% czasu na omówienie zagadnienia / problemu, reszta na implementacje (step by step).
Nie zamierzam przekroczyć 20 minut - lubię jak prelekcje są zwięzłe, zainteresowane osoby mogą porozmawiać ze mną po prezentacji :)

**Comment by naugtur** [comment]
To doprecyzuję - czego będzie więcej: pisania obsługi messengera czy pisania logiki bota?
Jaki masz plan na oszukiwanie podczas livecodingu? :)

**Comment by MateuszRojecki** [comment]
Pół na pół tego i tego.

Plan mam taki, że będę miał odpowiednio przygotowaną prezentację do tego - poszczególne kroki żeby zrobić prostego bota (animowane podświetlanie najważniejszych elementów kodu itp).

Kiedy planowany termin meet.jsa w PZN?

**Comment by naugtur** [comment]
Obstawiam że pod koniec września albo na początku października.

**Comment by SebastianPozoga** [comment]
Temat prezentacji zmienił się na "BackstopJS". To nie to samo ale nie ma innego tamatu więc dodaję tutaj.
Nagrania już są: http://events.pozoga.eu/meet-js-luty-2017/

**Comment by erykpiast** [comment]
@mattrojecki poproszę slajdy żebym mógł zamknąć issue.

**Comment by erykpiast** [comment]
@mattrojecki wrzucisz slajdy?

**Comment by erykpiast** [comment]
ping @mattrojecki

**Comment by erykpiast** [comment]
@mattrojecki zamykam temat bez slajdów :( :( :(
