### ISSUE TITLE
Angular 2 final release - co nowego, jak korzystać

### ISSUE THREAD

**Issue by Choniawko** [meetjspl/poznan#21]
Angular 2 wszedł w fazę final release. Myśle że to dobry moment na wystąpienie o tym jak aktualnie wyglada framework jak z niego korzystać, na czy się skupić a na czym mniej. Mało jeszcze zostało powiedziana na meet.js na ten temat, ja od kilku miesięcy pracuje na codzień z tym frameworkiem dlatego chciałbym coś o  tym powiedzieć. Jeśli macie jakieś uwagi wytyczne czego nie powinno zabraknąć w tej prezentacji to czekam na info :)

**Comment by SebastianPozoga** [comment]
Nagrania z prezentacji:
http://events.pozoga.eu/meet-js-32/

**Comment by erykpiast** [comment]
@Choniawko mógłbym prosić o podlinkowanie slajdów? Chciałbym zamknąć issue.
