### ISSUE TITLE
Metodologia BEM

### ISSUE THREAD

**Issue by bigsergey** [meetjspl/poznan#22]
Metodologia BEM: po co stosować, jak robić to dobrze? Rozwiązania najczęstszych błędów i problemów.
P.S. Mogę zaprezentować na meet.js Poznań 32

**Comment by erykpiast** [comment]
Wpisuję Cię na listę prelegentów.

**Comment by lukaszklis** [comment]
@bigsergey dasz radę wrzucić slajdy + nagranie po wystąpieniu? Niestety, ale nie dam rady do Poznania przyjechać, a chciałbym usłyszeć, co inni mają do powiedzenia na temat BEMa. :)

**Comment by bigsergey** [comment]
@lukaszklis Slajdy na pewno wrzucę, natomiast nagranie pewnie @SebastianPozoga.

**Comment by naugtur** [comment]
Przygotuj się na pytania o porównanie z innymi, prostszymi. Ja bym zapytał ;)

**Comment by bigsergey** [comment]
@naugtur Dzięki, przygotuję się na takie pytanie ;)

**Comment by bigsergey** [comment]
Dzięki za możliwość zaprezentowania się. [Link](http://slides.com/sergeybolshov/deck) do prezentacji.

**Comment by erykpiast** [comment]
Bardzo dobry talk, gratulacje! Zamykam issue.

**Comment by SebastianPozoga** [comment]
Nagrania z prezentacji:
http://events.pozoga.eu/meet-js-32/
