### ISSUE TITLE
What’s all the fuss about React Native?

### ISSUE THREAD

**Issue by sand25** [meetjspl/poznan#24]
Cześć!

Chciałbym się podzielić z Wami doświadczeniem w codziennej pracy z React Native. Będzie ciekawie i z nutką humoru, ale przedstawię też kilka nieprzyjemnych doświadczeń podczas obcowania zarówno z RN jak i samymi platformami mobilnymi.

W skrócie:
- w jaki sposób RN pozwala skupić się na faktycznym rozwiązywaniu problemów użytkowników, a nie zajmowaniu się z problemami technologii,
- co można osiągnąć w RN po kilku dniach zabawy czyli jak dorobić się MVP bez zgrzytania zębami i stresu przed deadlinem,
- kilka słów o animacjach i dążeniu do magicznych 60 fps,
- biblioteki komponentów, themes,
- debugowanie, testowanie i share’owanie aplikacji (w tym exponent),
- (opcjonalnie, tj. jeśli starczy czasu) realm i komunikacja realtime.

Pozdrawiam. :)

**Comment by erykpiast** [comment]
Jaką formę planujesz? Prezentacja z przykładami kodu, livecoding? Zupełnie nie wiem, w jaki sposób można na komputerze zaprezentować rezultat działanie takiej apki :) Są jakieś emulatory, czy chcesz podłączać telefon do rzutnika? :D

**Comment by bigsergey** [comment]
@sand25 Jeszcze fajnie by było opowiedzieć czy trzeba umieć pisać w Objective C, gdy zachodzi potrzeba tworzenia customowych komponentów.

**Comment by sand25** [comment]
@erykpiast Prezentacja z krótkimi przykładami. ;) Live coding odpada. Zwykle jest drętwo i nie pokaże się nic poza "Enterprise" Hello World. Symulator iOSa bardzo dobrze działa i na tym raczej poprzestanę. Można podłączyć telefon do rzutnika, zależy od modelu. Nie bawiłem się tym jednak, żeby ryzykować. :P
@bigsergey Będzie. Spoiler alert: bardzo rzadko. Dotychczas z moich obserwacji wynika, że trochę więcej w Javie - RN jest nieco dojrzalszy na iOSa (kwestia pewnie czasu - najpierw był przygotowany pod ten system, dopiero później Androida).

**Comment by erykpiast** [comment]
@sand25 świetnie! Potrzebujesz jakiejś pomocy? Chciałbyś żebyśmy obejrzeli prezentację (slajdy, notatki) jeszcze przed meetupem?

**Comment by sand25** [comment]
@erykpiast z chęcią. ;) Jakbyś dał jakiś namiar, to byłoby super. Jak ogarnę temat na spokojnie w najbliższych dniach, to dam znać.

**Comment by erykpiast** [comment]
Super! Jak będziesz gotowy, wyślij po prostu materiały na `poznan@meetjs.pl`, będziemy kontynuować konwersację mailowo. Tu zostawmy przestrzeń do dyskusji dla innych :)

**Comment by bigsergey** [comment]
@sand25 Będzie coś o tym jak się robi animację w React Native?

**Comment by sand25** [comment]
@bigsergey Nie chcę mocno się skupiać na animacjach w tej prezentacji, bo jest to temat bardzo rozległy i można z tego stworzyć oddzielną prezkę, a nawet zbudować wokół tego cały workshop, szczególnie gdy nie miało się wcześniejszego doświadczenia z czymś w stylu react-motion czy GSAP. Oczywiście nie sposób nie wspomnieć o layout animations czy InteractionManager, ale tłumaczenie jak tworzyć animacje krok po kroku to nie ten scope imho. :) Jeśli masz coś jednak konkretniejszego na myśli, to wal śmiało. ;)

**Comment by bigsergey** [comment]
@sand25 dzięki za odpowiedź, chodziło mi tylko o ogólne powiedzienie, że robi się podobnie do GSAP oraz jakie narzędzia są wykorzystywane. W sumie to co napisałeś tutaj mnie satysfakcjonuję :)

**Comment by SebastianPozoga** [comment]
Nagrania już są: http://events.pozoga.eu/meet-js-luty-2017/

**Comment by erykpiast** [comment]
@sand25 poproszę o link do slajdów i zamykam issue.

**Comment by sand25** [comment]
http://slides.com/przemekmurawski/rn

**Comment by erykpiast** [comment]
Dzięki!
