### ISSUE TITLE
from REST to Lambda architecture and beyond!

### ISSUE THREAD

**Issue by sihingkk** [meetjspl/poznan#25]
W tym roku czeka nas wysyp talków "rest is dead" itp. A ja bym chciał od innej strony - jak dużo prościej można podejść do architektury naszych aplikacji i dostać bardzo tanio architekturę lambda dla frontendu bez posiadania skali (i budżetu!) Spotify.

**Comment by naugtur** [comment]
Jaka forma? Planujesz jakieś demo lub livecoding?
Nie odbierz tego jak sugestii, livecoding w tym przypadku raczej nie ma sensu, ale chętnie się dowiem w jakiej formie planujesz to pokazać.

Lambda zawsze chętnie :)

**Comment by erykpiast** [comment]
@sihingkk czy temat jest aktualny z Twojej strony? pytam, bo minęło trochę czasu od założenia issue.

**Comment by erykpiast** [comment]
Zamykam z braku odzewu.
