### ISSUE TITLE
Introduction to ReactVR

### ISSUE THREAD

**Issue by tomaszlakomygp** [meetjspl/poznan#26]
Chciałbym opowiedzieć krótko o ogłoszonym przez FB w październiku 2016 React VR. Projekt jest w fazie alpha, ale wydaje mi się na tyle ciekawy, że warto się tym trochę pobawić :)

**Comment by naugtur** [comment]
Spoko temat. Jak chcesz to pokazać?

Pasuje Ci termin w ostatnich dniach stycznia?

**Comment by tomaszlakomygp** [comment]
Planowałem coś na wzór prezentacji o Electronie z ostatniego (?) poznańskiego meet.js, czyli prezentacja + live demo. Nie będę zbyt długo mówił, bo sam ReactVR się jeszcze rozwija.

Co do terminu - pasuje mi dopiero po 26 stycznia.

**Comment by naugtur** [comment]
@erykpiast next a nie 7 lutego?

**Comment by erykpiast** [comment]
no, źle mi się kliknęło ;)

**Comment by tomaszlakomygp** [comment]
@naugtur @erykpiast to mój pierwszy talk na meet.js, jest coś o czym powinienem wiedzieć/zrobić przed?

**Comment by tomaszlakomygp** [comment]
Ołrajt, swoją drogą taki mały disclaimer: nie posiadam Oculus Rifta, bo osobiście czekam aż domowy VR trochę dojrzeje. Swojego talka będę bazować na tym co można pokazać/zrobić w przeglądarce :)

**Comment by erykpiast** [comment]
chyba jednak niewiele osób posiada takie urządzenie, więc to może nawet lepiej :D

**Comment by naugtur** [comment]
Jest szansa, że działa to na telefonie tak jak AFrame od mozilli i jest kompatybilne z cardboardem.
Jak chcesz sprawdzić to mam cardboarda i plastikową wersję z biedronki ;)

Poza tym (napiszę bo i tak mało kto tu patrzy) planuję pod koniec lutego biletowany meet.min.js o webVR, na który masz wstęp bez kolejki.

A w temacie co wiedzieć przed pierwszym razem
- nie próbuj livecodingu jeśli nie masz sprytnego planu - ludzie nie chcą patrzeć jak wpisujesz tekst
- będziesz mówił dłużej niż Ci się wydaje
- w kwestii czego pokazać więcej a czego mniej - pokaż nam prezentację jeśli już masz, albo pogadajmy 5 minut na hangoutach

Generalnie najlepszym co możesz zrobić dla jakości swojego wystąpienia to trzy inne wystąpienia przed nim :D

**Comment by tomaszlakomygp** [comment]
Dzięki za wejsciowke na meet.min.js, doceniam!

Na telefonie jak najbardziej działa, prawdopodobnie będę też mieć Gear VR ze sobą. Livecodingu nie planuję, React VR działa zwyczajnie zbyt wolno na livecoding.

Oficjalnego supportu dla cardboarda nie ma, ludzie od Reacta zapytani o support powiedzieli, że proszą o issue na githubie, także tego.

Pytanko - czy mogę polegać na wifi na miejscu? Chciałbym streamować obraz z telefonu na kompa, żeby pokazać go widzom.

**Comment by naugtur** [comment]
Wifi nie sprawiało nigdy problemów, a jeśli łączysz się po sieci lokalnej to w ogóle powinno pójść gładko. 
Najlepiej zrobić test na miejscu. Ja zwykle jestem co najmniej 30 minut przed czasem.

**Comment by tomaszlakomygp** [comment]
Dobra, to będę o 17:30 na miejscu!

**Comment by SebastianPozoga** [comment]
Nagrania: http://events.pozoga.eu/meet-js-luty-2017/
(jeszcze trwa upload więc pewnie będą dostępne za jakieś 30min)

**Comment by erykpiast** [comment]
@tomaszlakomygp poproszę o link do slajdów i zamykam issue.

**Comment by tomaszlakomygp** [comment]
Slajdy: https://docs.google.com/presentation/d/1K_rLhAknJvTucOFc92MSyj2VgqP9FCwTAHheXPxx6Hs/edit?usp=sharing

Dzięki za zaproszenie, jak wymyślę temat na kolejną prelekcję to dam znać!

**Comment by erykpiast** [comment]
Koniecznie! :)
