### ISSUE TITLE
Change detection in Angular 2

### ISSUE THREAD

**Issue by adrianmroz** [meetjspl/poznan#27]
O tym jak nowy angular wykrywa zmiany i decyduje co przerenderować. Jak możemy mu pomóc za pomocą immutabli i observabli i różnych strategii dostępnych dla usera.

**Comment by naugtur** [comment]
A obiecujesz, że zrozumiem? ;)

**Comment by adrianmroz** [comment]
Zrobię co w mojej mocy!

**Comment by SebastianPozoga** [comment]
Nagrania już są na:
http://events.pozoga.eu/meet-js-34/

**Comment by adrianmroz** [comment]
https://www.dropbox.com/s/e19vtxwgs51ujmv/change-detection.pdf?dl=0

**Comment by erykpiast** [comment]
Dzięki za nagrania i slajdy! Super prezentacja, mimo, że zapowiadała się nieciekawie :P Zamykam issue.
