### ISSUE TITLE
Meet.min.js VR

### ISSUE THREAD

**Issue by naugtur** [meetjspl/poznan#28]
Co będzie:
- AFrame od Mozilli - wprowadzenie i przykłady [Zbyszek Tenerowicz]
- Wspólne eksperymenty z VR w przeglądarce - zabierzcie laptopy i telefony
- Egnyte sponsoruje piwo i parę cardboardów (będzie można je wygrać)

Kiedy: Piątek 17 marca 18:00

Gdzie: Egnyte Loft, Mostowa 11

Zapisy: Mamy 20 miejsc. Napisz komentarz poniżej żeby się zapisać. W komentarzu napisz czy masz cardboarda lub podobne urządzenie typu okulary VR.

Poza kolejką i limitem miejsc przyjmujemy prelegentów wcześniejszych Meet.js 

(Edit)
Okulary nie są konieczne, i tak będziemy eksperymentować w małych grupach. Jedne na trzech wystarczą.

(Edit) Tomek Łakomy wystąpi też w roli mentora React VR, będzie można wypróbować również Reactową wersję.

(Edit) Egnyte podbija stawkę, będzie też pizza ;)

**Comment by belfz** [comment]
Zgłaszam się. Cardboarda, niestety nie posiadam.

**Comment by przemyslawjanpietrzak** [comment]
Zgłaszam się, mam cardboarda.

**Comment by soquel** [comment]
Zglaszam sie, mam cardboarda i to cos smieszne z biedronki.

**Comment by Thorleon** [comment]
Zgłaszam się, cardboarda brak.

**Comment by tomaszlakomygp** [comment]
Będę, cardboarda mam.

**Comment by tiriana** [comment]
Zgłaszam się, mam cartboarda


09.03.2017 12:32 AM "Tomasz Łakomy" <notifications@github.com> napisał(a):

**Comment by wolasss** [comment]
Zgłaszam się, cardboarda nie mam.

**Comment by uhlryk** [comment]
Zgłaszam się, nie ma cardboarda

**Comment by danielsaf** [comment]
https://github.com/meetjspl/poznan/issues/28

**Comment by mstankowiak** [comment]
Zgłaszam się, brak cardboarda.

**Comment by lebrande** [comment]
Zgłaszam się. Brak cardboarda.

**Comment by bigsergey** [comment]
Zgłaszam się. Brak cardboarda.

**Comment by Progowi** [comment]
Zgłaszam się. Brak cardboarda.

**Comment by Arturszott** [comment]
Zgłaszam się. Cardboard gdzieś się znajdzie.

**Comment by mercs600** [comment]
Zgłaszam się, brak cardboarda

**Comment by Suiseki** [comment]
Zgłaszam się, bez cardboarda,

**Comment by hoffmannjan** [comment]
Ja też się zgłaszam, z cardboardem

**Comment by dzastaa92** [comment]
Zgłaszam się, brak cardboarda

**Comment by Yog** [comment]
Zgłaszam się, nie mam cardboarda.

**Comment by Ortee** [comment]
🚀 Zgłaszam się. Brak cardboarda.

**Comment by xkxd** [comment]
zgłaszam się, cardboarda mam.

**Comment by patrykziem** [comment]
Zgłaszam się, mam Gear VR (nie wiem czy pomaga).

**Comment by indianer** [comment]
Zgłaszam się, brak cardboarda

**Comment by naugtur** [comment]
----
Miejsca w zapisach wyczerpane.

Można się jeszcze dostać jeśli:
- jesteś prelegentem Meet.js
- przyniesiesz ciekawy hardware do VR

----
Jeśli chętnych będzie więcej, możemy zrobić podobny event za miesiąc-dwa. Więc piszcie komentarze dalej, jak się uzbiera następne 20 osób, to pogadamy.

**Comment by patrykziem** [comment]
W biurze powinniśmy mieć dwa Oculusy DK2, zabrać ze sobą?

**Comment by naugtur** [comment]
Jeśli masz jak, to pewnie! Zobaczymy czy Oculus ma przeglądarkę i co potrafi.
Myślę, że Gear VR i Oculus to i tak sporo noszenia, nie dźwigaj drugiego oculusa :)

**Comment by tomaszlakomygp** [comment]
Oculus jak najbardziej ma przeglądarkę, apki w ReactVR można na tym odpalać chociaż w praktyce nie testowałem

**Comment by kr1zr** [comment]
Mam kilka cardboard'ów i chętnie przyniosę na następne spotkanie. Strasznie żałuję, że na to nie zapisałem się odpowiednio szybko :(.

**Comment by naugtur** [comment]
Jak ktoś odpadnie, to jesteś pierwszy ;) obserwuj wątek

**Comment by djlann** [comment]
Zgłaszam się. Brak cardboarda.

**Comment by tomaszlakomygp** [comment]
@naugtur Jeżeli będzie czas, chęci i zainteresowanie to chętnie powtórzę swoją prezkę z ostatniego meet.js o ReactVR. Można też zrobić wersję min.js, tylko najważniejsze rzeczy - tak dla przypomnienia :)

**Comment by naugtur** [comment]
@tomaszlakomygp zobaczymy ile osób nie widziało jej za pierwszym razem. Jeśli nie widzieli, to warto streścić.

**Comment by danielsaf** [comment]
Przepraszam, ale nie dam rady przyjść więc zwalniam miejsce. Muszę zostać w domu. Byłem 9:) Proszę zdecydować kto jest kolejny.

**Comment by mercs600** [comment]
Hej, ja tez nie dam rady dotrzeć, choroba mnie dopadła :/

**Comment by Progowi** [comment]
Ja się zapisałem ale nie wiem czy dam radę dotrzeć, więc jak ktoś chce to oddam miejsce, jak nikt się nie zgłosi to będę starał się zdążyć.

**Comment by naugtur** [comment]
@kr1zr @djlann Dostaliście miejsca, zapraszam jutro. :)

**Comment by djlann** [comment]
@naugtur wpadnę, dzięki!

**Comment by Ortee** [comment]
Niestety zwalniam slota i czekam na next meeting :)

**Comment by grzegorzkruk** [comment]
Jest jeszcze wolne miejsce? Chciałbym bardzo przyjść. Przyniosę gogle Gear VR.

**Comment by naugtur** [comment]
Jest miejsce. @grzegorzkruk

**Comment by dzastaa92** [comment]
Niestety nie mogę dzisiaj przyjść, zwalniam miejsce.

**Comment by grzegorzkruk** [comment]
Super. Zgłaszam się na to miejsce. :)

**Comment by naugtur** [comment]
@Progowi nie ma kar za spóźnienie ;)

**Comment by naugtur** [comment]
Przypomnienie:

Weźcie laptopy, będziemy pisać kod, nie tylko oglądać efekty ;)

Pair programming spoko, ale w 20 osób może być ciężko. :)

**Comment by HubertPodgorski** [comment]
Piszę się, jeśli ciągle jest miejsce :) (nie posiadam cardboarda)

**Comment by hoffmannjan** [comment]
Ja jednak też ostatecznie odpadam, wyskoczyło mi pare niespodziewanych rzeczy, mam nadzieje że następnym razem się uda.

**Comment by olarybacka** [comment]
Ja też poproszę miejsce rezerwowe (brak cardboarda)

**Comment by djlann** [comment]
Jestem zmuszony oddać swoje miejsce. Liczę, że jeszcze odbędzie się tego typu spotkanie.

**Comment by wolasss** [comment]
Ja niestety nie zdążę dojechać dzisiaj do Pzn, więc zwalniam swoje miejsce.

**Comment by patrykziem** [comment]
Ja też jestem zmuszony zrezygnować (chociaż byłem poza limitem, więc chyba nie pomagam nikomu :p). Oculusa, o którym mówiłem weźmie ze sobą Sergey.

**Comment by naugtur** [comment]
@HubertPodgorski @olarybacka miejsca są, przychodźcie!

**Comment by kr1zr** [comment]
szlag T_T @naugtur  dzięki bardzo za opcję ,ale byłem już offline przez kolejne kilkanaście godzin. Będę czatował na kolejne spotkanie, mam nadzieję, że wszyscy zaproszeni wraz z hostami sporo ze spotkania wyciągnęli :)

**Comment by erykpiast** [comment]
@naugtur chcesz tu wrzucić jakieś materiały, czy mogę zamknąć issue?

**Comment by naugtur** [comment]
Mam tylko kilka fotek :)
