### ISSUE TITLE
Do we really need WASM?

### ISSUE THREAD

**Issue by P0lip** [meetjspl/poznan#29]
O tym dlaczego WASM może pomóc webowi w wielu przypadkach. Jego zalety (i wady) nad JSem.

**Comment by naugtur** [comment]
Temat na czasie. 
Proponuję też porównanie z asm.js bo idea podobna ale baaardzo się różnią konsekwencjami.

**Comment by tiriana** [comment]
Piszę się na taki temat rękami i nogami, bardzo chętnie posłucham i dowiem
się więcej.

2017-04-11 18:28 GMT+02:00 Zbyszek Tenerowicz <notifications@github.com>:

**Comment by SebastianPozoga** [comment]
Nagrania już są na:
http://events.pozoga.eu/meet-js-34/

**Comment by erykpiast** [comment]
@P0lip mógłbyś wrzucić slajdy?

**Comment by P0lip** [comment]
[Prezentacja](https://docs.google.com/presentation/d/1e_AsiB2TjbycWxkAgZQf3ogeCSXUqsGEER6LPMjTx94/edit?usp=sharing)

Done :)

**Comment by erykpiast** [comment]
Super, dziękuję!
