### ISSUE TITLE
Transducers: intro, zasada działania, użycie w przetwarzaniu kolekcji

### ISSUE THREAD

**Issue by adrianmroz** [meetjspl/poznan#3]
Wstęp do (wady, zalety, filozofia i ogólne zasady działania) i przykłady użycia transducerów, które przyszły z  [Clojure](http://clojure.org/transducers). Skupiłbym się na implementacji [Cognitecta](https://github.com/cognitect-labs/transducers-js) i przede wszystkim ich użyciu do transformacji kolekcji (użycie w natywnym reduce, immutable.js i klasycznym lodash/ramda). Dodatkowo bym wspomniał o ich użyciu w innych kontekstach - channelach, leniwych sekwencjach i observablach, ale to już koncepcyjnie, bo bez wymagań co do znajomości tych kontekstów.

**Comment by erykpiast** [comment]
super pomysł!

**Comment by naugtur** [comment]
Robi wrażenie.
Ile czasu potrzebujesz na przygotowanie? Możemy rozmawiać o najbliższym meecie? (poczatek października)

**Comment by adrianmroz** [comment]
Tak, miałem na myśli ten najbliższy meet. Powinienem być gotowy na tyle, na ile można być gotowym na pierwszej konferencji!

**Comment by naugtur** [comment]
That's the spirit! :)

**Comment by adrianmroz** [comment]
Slajdy: http://slides.com/dhucerbin/transducers#/

**Comment by erykpiast** [comment]
powtórzę to raz jeszcze: bardzo dobra prezentacja! :+1:

**Comment by SebastianPozoga** [comment]
Prezentacja dostępna na:
http://events.pozoga.eu/meet-js-poznan-10-2015/
