### ISSUE TITLE
AdTalk: ad-tech na przykładzie Fandom

### ISSUE THREAD

**Issue by nandy-andy** [meetjspl/poznan#30]
Wpisując kilka tygodniu do Google'a "ad tech conferences" chciałem znaleźć konferencję dla developerów, którzy zawodowo pracują z reklamami. Okazało się to dość trudne, zapytałem więc bardziej doświadczonych kolegów, czy jest takie Velocity, albo CraftConf ale o tym czym my się zajmujemy i ze smutkiem dostałem odpowiedź, że nic o tym nie słyszeli.

W związku z tym pomyślałem, że warto byłoby sprawdzić lokalnie, czy ludzi interesuje taki temat i być może samemu stworzyć coś wielkiego - wspólnie :-) Ta prezentacja może być pierwszą z wielu, albo pierwszą i jedyną - wszystko zależy od Waszego feedbacku. Chciałbym opowiedzieć o tym jak w Fandomie wygląda praca w Ad Engineeringu i przytoczyć ogólnie takie tematy jak:
* DFP (DoubleClick for Publishers) w małej/średniej skali i w dużej,
  * line-items, creatives, 
  * targetowanie,
  * security,
* inne serwery reklamowe (OpenX),
* header-bidding (prebid.js),
* "ads recovery",
* direct ads products
  * IAB (Interactive Advertising Bureau),
  * viewability,
* reklamy a web performance,
  * direct ads,
  * ad networks,
  * AMP (Accelerated Mobile Pages).

Punkty powyżej nie są już "zaklepaną", wyrytą w kamieniu agendą. Jest to bardziej mój brain-dump i w najbliższych dniach będzie ewoluował z Waszą pomocą aż stworzymy coś, o czym chcecie posłuchać :-)

**Comment by tomaszlakomygp** [comment]
Brzmi mega, bardzo chętnie posłucham!

**Comment by tniezurawski** [comment]
Nigdy nie zajmowałem się reklamami i większość słów/pojęć jest mi nieznana. Z wielką przyjemnością posłucham wprowadzenia do tematu.

**Comment by erykpiast** [comment]
AMP - bardzo. Tracking efektywności? Czy to tylko clicki, czy jakieś bardziej wysublimowane metryki (i co za tym idzie, narzędzia?)

**Comment by nandy-andy** [comment]
@erykpiast niestety pewnie Ciebie zmartwie, bo wrzucilem AMP do kategorii "reklamy a web performance" i raczej chcialem o tym wspomniec jako "nadzieja" na przyszlosc (byc moze udaloby mi sie zachecic chlopakow z innego zespolu, ktorzy przeprowadzali testy dla naszej mobilnej skorki i sprawdzali AMP; ale to juz bylby raczej osobny talk, gdyby sie chetny znalazl ;-))

**Comment by SebastianPozoga** [comment]
Nagrania już są na:
http://events.pozoga.eu/meet-js-34/

**Comment by erykpiast** [comment]
@nandy-andy podlinkujesz tu slajdy?

**Comment by nandy-andy** [comment]
Jasne! https://docs.google.com/presentation/d/1phVWJ2XORgEJ5n17XefjITRp2Xlg9Wz3rnan54YWNZw

**Comment by erykpiast** [comment]
Super, dzięki! Zamykam issue.
