### ISSUE TITLE
node 7 async await with koa2

### ISSUE THREAD

**Issue by speedingdeer** [meetjspl/poznan#32]
Ostatnio startowaliśmy z nowym projektem i zamiast klasycznie postawić to na expresie, użyliśmy koa2 + babel z całym dobrodziejstwem async await. Jest kilka ciekawostek do opowiedzenia i kilka problemów do naświetlenia :)

Alternatywne tematy związane z tym projektem pozostające w tematyce node.js:
- koa2 REST API for ember app (jak zamodelować DS store i API żeby wszystkie meta dane i relacje pobierały się autoamtycznie)
- web scrapping with preview (nightmare.js)

**Comment by naugtur** [comment]
Obiektywnie o async await byłoby spoko. Hajpu ludzie się już nasłuchali, a wspomnienia z pola bitwy są o wiele bardziej wartościowe. +1 for that. 

Drugi temat może zbyt specyficzny. Trzeci fajna ciekawostka.

**Comment by speedingdeer** [comment]
Dzięki za komentarz.
Tak, wydaje mi się, żę async await można ciekawie przedstawić na kilku przykładach w stylu 'co zostanie przypisane po ...' szczególnie jeśli wejdzie się w jakieś zagnieżdżenia itd. to przestaje być bardzo oczywiste.

**Comment by naugtur** [comment]
Error handling z zagnieżdżeniem i recovery, porównane z promieni, polecam :p
Opinie są podzielone

**Comment by naugtur** [comment]
Promisami miało być

**Comment by speedingdeer** [comment]
brzmi dobrze! tak obsługa wyjątków z async await jest trochę mało intuicyjne. Podoba mi się ten temat.

**Comment by erykpiast** [comment]
@speedingdeer czy zechciałbyś przygotować temat na listopadowe spotkanie?

**Comment by speedingdeer** [comment]
Musiałbym to sobie troszeczkę odświeżyć ale myślę, że spoko. Zależy jakie długie by miało to być - mi się wydaję ze to powinno być krótkie i przede wszystkim pokazać, że to jest backward compatible a nie że jest połowa aplikacja napisana w node 7 a połowo w 6. To wszytko dalej działa.

**Comment by erykpiast** [comment]
Prezentacja powinna się zmieścić w 20 minut, więc zdecydowanie nie powinna być długa :)

**Comment by speedingdeer** [comment]
OK świetnie, to bardzo chętnie przygotuje.

**Comment by naugtur** [comment]
Jeśli chcesz się skonsultować przy przygotowaniu planu prezentacji i zdecydowaniu co pokazać i jak to pisz do mnie na maila :+1:

**Comment by speedingdeer** [comment]
@naugtur bardzo chętnie. W weekend złożę jakiś outline.

**Comment by erykpiast** [comment]
@speedingdeer czy chcesz kontynuować temat? np. żeby zrobić prezkę w lutym?

**Comment by naugtur** [comment]
@speedingdeer ping.
Mamy termin na 2 marca. Jesteś zainteresowany wystąpieniem wtedy?

**Comment by speedingdeer** [comment]
Tak chętnie :)

2018-02-15 22:57 GMT+01:00 Zbyszek Tenerowicz <notifications@github.com>:

**Comment by speedingdeer** [comment]
@erykpiast przepraszam, uciekł mi Twój komentarz, @naugtur dzięki za ping

**Comment by speedingdeer** [comment]
https://github.com/speedingdeer/meetjs-koa
https://docs.google.com/presentation/d/1fQGMrFqn6FPnWzIfCzhhX_FC5f_7l2VV4lM_cU-VBac

**Comment by erykpiast** [comment]
Cudownie, że nie musiałem przypominać o slajdach :D Super prezentacja, dzięki!

**Comment by speedingdeer** [comment]
do usług :)
