### ISSUE TITLE
Wdrożenie React Native w istniejącej aplikacji Allegro iOS

### ISSUE THREAD

**Issue by qzim** [meetjspl/poznan#33]
1. Co jest nie tak z natywną developerką i dlaczego potrzebujemy RN
2. Integracja RN z kilkuletnim codebase
3. JS, React, React Native z punktu widzenia programisty iOS
4. Napotkane problemy i zastosowane rozwiązania
5. Opis rezultatu, porównanie z natywną implementacją.
6. Wnioski i następne kroki.

**Comment by naugtur** [comment]
na react meetup we wrześniu w sam raz :)

**Comment by piotros** [comment]
Temat wygląda na prawdę zacnie! Wielka prośba o nagranie tej prelekcji i wrzucenie na youtube.

**Comment by naugtur** [comment]
@piotros a może jednak przyjdziesz? ;)

**Comment by piotros** [comment]
@naugtur chciałbym, ale mam do Was jakieś 500 kilometrów ;)

**Comment by naugtur** [comment]
Poznańskie spotkania od dawna nagrywa Sebastian Pożoga http://events.pozoga.eu
Link do nagrania trafi tu jako komentarz.

**Comment by piotros** [comment]
Super! Dzięki! :+1:

**Comment by SebastianPozoga** [comment]
Nagrania http://events.pozoga.eu/meet-js-react/

**Comment by erykpiast** [comment]
@qzim wrzuć proszę link do prezentacji i możemy zamknąć issue :)

**Comment by qzim** [comment]
[meetup_RN.pdf](https://github.com/meetjspl/poznan/files/1386872/meetup_RN.pdf)
