### ISSUE TITLE
React Design Patterns

### ISSUE THREAD

**Issue by jankowiakdawid** [meetjspl/poznan#34]
Zebranie i podsumowanie patternów componentyzacji aplikacji Reactowych

* Higher Order Components
* Function As a Child (Render function)
* Compound State
* Reducer Components

Gdzie jakiego użyć, jak zaimpelementować, mocne słabe strony.

**Comment by tiriana** [comment]
Słuchałbym.

**Comment by naugtur** [comment]
Wygląda bardzo dobrze.

Upewnij się, że do każdego masz czytelny przykład i mimo to zmieścisz się w 20-25 minut. Powinno się udać, ale zawsze polecam sprawdzić. 

Dorzucimy Cię do agendy na reactowe spotkanie za ~tydzień, tylko potwierdź że będziesz gotowy.

**Comment by jankowiakdawid** [comment]
@naugtur będę gotowy 😉

**Comment by naugtur** [comment]
Super. Jakbyś czegoś potrzebował to pisz tu lub na maila

**Comment by SebastianPozoga** [comment]
Nagrania http://events.pozoga.eu/meet-js-react/

**Comment by erykpiast** [comment]
@jankowiakdawid wrzuć proszę link do prezentacji i możemy zamknąć issue :)

**Comment by jankowiakdawid** [comment]
https://speakerdeck.com/jankowiakdawid/react-component-patterns
