### ISSUE TITLE
Functional Reactive Programming - od podstaw. Modelowanie danych.

### ISSUE THREAD

**Issue by adrianmroz** [meetjspl/poznan#35]
Hej. Chciałbym opowiedzieć o podstawowych definicjach w FRP, w szczególności o modelowaniu danych. Dla równowagi - przykłady w Angularze i Rx.js, ale będzie bardzo ogólnie. 

Chcę pokazać jak modelować dane za pomocą `Behaviour`ów i udowodnić, że to prostszy model niż `Event`y. Oraz jak w trudniejszych przypadkach zejść do `Event`ów i zachować ogólność. Wszystko na przykładzie starannie dobranego do tezy komponentu :) Jakiś datepicker albo filtrowany multi-select.

**Comment by naugtur** [comment]
A dałoby się zrobić logikę bez komponentu i potem pokazać że ta sama logika się dobrze wpina i do angulara i do reacta z reduxem i do vuejs? To by sprzedało temat

**Comment by adrianmroz** [comment]
Konkretna implementacja komponentów jest nieważna, zaś sam widok jest abstrakcyjny. Mogę zarówno pokazać generyczny framework z wąsatymi templatkami albo JSX. To czy dane są na instancji komponentu angularowego czy dopiero w propsach/state reactowego będzie całkowicie nieważne.

Redux to zbyt odległy temat, ale napomknę o mobx.

Ogólnie rozumiem o co Ci chodzi i też chciałbym w ramach czasowych zachować jak najbardziej generalną wiadomość i nie wnikać w szczegóły frameworków w zasadniczej części prezentacji.

**Comment by erykpiast** [comment]
Czyżby nazwa sugerowała serię prezentacji?

**Comment by erykpiast** [comment]
@adrianmroz wyrobisz się na połowę listopada? :)

**Comment by adrianmroz** [comment]
Tak.

**Comment by erykpiast** [comment]
@adrianmroz wrzucisz slajdy?

**Comment by adrianmroz** [comment]
https://www.dropbox.com/s/gi86t8uuk7f1yqz/frp.pdf?dl=0

**Comment by erykpiast** [comment]
❤️

**Comment by SebastianPozoga** [comment]
Nagrania prezentacji

http://events.pozoga.eu/meet-js-poznan-36/
