### ISSUE TITLE
Boosting the store with redux middlewares

### ISSUE THREAD

**Issue by Arturszott** [meetjspl/poznan#36]
1. Przedstawienie konceptu middleware.
2. Najprostsza implementacja
3. Bardziej zaawansowana implementacja
4. Dlaczego redux-thunk jest słabo testowalny
5. Przykłady użycia różnych middleware - google analytics, notyfikacje, router.

**Comment by SebastianPozoga** [comment]
Nagrania http://events.pozoga.eu/meet-js-react/

**Comment by erykpiast** [comment]
@Arturszott wrzuć proszę link do prezentacji i możemy zamknąć issue :)

**Comment by Arturszott** [comment]
https://docs.google.com/presentation/d/1MWihwJPDtjTqTK3B7ZZqZQPjOqdZ-zAfDBRXXrBQMDA/edit?usp=sharing
