### ISSUE TITLE
Introduction to Firebase using React Native

### ISSUE THREAD

**Issue by Krizzu** [meetjspl/poznan#37]
Cześć!

Chciałbym zgłosić się jako prelegent na następny meetup. Jakieś info o najbliższej dacie?
Czy talk może być w języku angielskim?

Talk:
- What is Firebase?
- Setup a RN project with native implementation of Firebase 
- Implementing authentication
- Using real time database database

Dzięki!

**Comment by erykpiast** [comment]
Fajny temat!

Dobrze byłoby powiedzieć, czym w ogóle jest serverless architecture i że firebase to tylko jedno z podejść do tematu.

Zastanawiam się też, ile rzeczywiście kodu jest potrzebne do podstawowej implementacji w RN, czy jako osoba, która nie zna platformy mobilnej, nie zgubię się w jakichś nieistotnych, ale nieintuicyjnych szczegółach?

**Comment by Krizzu** [comment]
O samym serverless chciałem omówić w pierwszym podpunkcie, oczywiście wspominając o innych rozwiązaniach niż Firebase.

A co do instalacji RN, myślę, że może być to trochę 'odpychające', jednak jest to zwykłe dodanie modułów do builda. Gdy raz już się doda Firebase core i odpowiadające nam moduły (jeżeli któregoś nie planujemy używać, to możemy pominąć), nie ruszamy więcej strony natywnej, tylko JS.

**Comment by erykpiast** [comment]
Czyli prezentację zaczniesz z jakiś stanem wyjściowym, apka (jakiś boilerplate) już działa i chcemy dodać Firebase, tak?

**Comment by Krizzu** [comment]
CLI `react-native init` postawi nam 'czystą' apke, gotową do odpalenia. Opowiem krótko o strukturze plików i potem dodamy firebase (fake-live-programming).

**Comment by Krizzu** [comment]
Cześć,

Nic nie szkodzi. Myślę, że na chwilę obecną nieaktualne :)

**Comment by erykpiast** [comment]
Okej, dzięki za update! Na razie zamykam temat. Gdybyś miał inny, zgłaszaj. Ogarniemy bardziej i przede wszystkim szybciej :)
