### ISSUE TITLE
Bot, cała historia!

### ISSUE THREAD

**Issue by stasm** [meetjspl/poznan#38]
Hej! Czy posłuchalibyście mojej historii o tym, jak zbudowałem prostego bota na Messengera? Rowerynka działa także w Poznaniu!

> Rowerynka to bot na Messengera, który potrafi odpowiedzieć na jedno pytanie: gdzie znajduje się najbliższy rower miejski? To prosty projekt (800 linii JavaScriptu!) którego wydanie od początku do końca zajęło 47 godzin. Czy to dużo? Opowiem o całym procesie twórczym: projekcie MVP, integracjach z API Facebooka i Google Maps, planowaniu 1.0, wyzwaniach, problemach i rozwiązaniach. Będzie trochę o async/await i maszynach stanu — ale przede wszystkim o tym, że wydawanie wersji 1.0 to wielka przygoda.

Dałem tę prezentację na katowickim meet.js w maju. Została dobrze przyjęta. Niestety jest dość długa: 45 minut. Potargujemy się? :)

**Comment by tiriana** [comment]
Słuchałbym

06.11.2017 10:45 "Staś Małolepszy" <notifications@github.com> napisał(a):

**Comment by soquel** [comment]
Słuchałbym 45 minut.

**Comment by speedingdeer** [comment]
Robiłem kiedyś co bardzo podobnego https://twitter.com/deepforger
Chętnie porównam doświadczenia 👍

**Comment by naugtur** [comment]
Brzmi jak dobra opowieść. 45 minut trochę dużo, można by odrobinę przyciąć. Jeśli masz fragmenty o konkretnych API maps, fb i innych, to można je trochę skipnąć - w końcu mają dokumentację. 

Jeśli mam się targować, to proponuję 35 minut. Myślisz, że da radę? :)

**Comment by stasm** [comment]
OK, postaram się coś wyciąć i przećwiczę. 35 minut powinno być okej.

O async/await mam już tylko jeden krótki slajd, o API chcę przede wszystkim powiedzieć to, że są i wymagają integracji. To nie jest techniczna prezentacja. Chcę przez nią pokazać, jak wygląda proces tworzenia działającej aplikacji od zera do 1.0. I że każde kolejne API to czytanie dokumentacji, testy, point of failure itd.

Slajdów jest dużo (ponad 140) ale są hasłowo-obrazkowe i służą za ilustrację to tego, co mówię. Więc tak akurat 15 sekund na slajd.

**Comment by iansowinski** [comment]
Wooo ja bym bardzo chętnie posłuchał, bo sam robię coś podobnego 👍

**Comment by erykpiast** [comment]
@stasm, wrzucisz slajdy? :)

**Comment by stasm** [comment]
Oczywiście: https://docs.google.com/presentation/d/1Id-WqQLtvBYUc9OAYjRek9d-QKit8yy99gWd-roHhLE/edit?usp=sharing

Dziękuję za gościnę i ciepłe przyjęcie!

**Comment by erykpiast** [comment]
To my dziękujemy! :)

**Comment by SebastianPozoga** [comment]
Nagrania prezentacji

http://events.pozoga.eu/meet-js-poznan-36/
