### ISSUE TITLE
immutable datastructures and react

### ISSUE THREAD

**Issue by sihingkk** [meetjspl/poznan#39]
chętnie bym pogadał na ten temat :)

plusy, minusy, żarciki, jak ugryźć ten temat z JS i skąd te pomysły.

chcecie?

**Comment by naugtur** [comment]
Chcemy. Wyjaśnienie _dlaczego_ warto używać i kiedy używanie mija się z celem (np. w przypadku konwertowania danych z innego źródła na immutable przed każdym renderem tylko po to, żeby później przyspieszyć porównania)

**Comment by erykpiast** [comment]
@sihingkk trochę wstyd odzywać się po przeszło roku, ale temat nadal wydaje się bardzo ciekawy, tym bardziej z perspektywy zmian, które zaszły w Reakcie przez ten czas. Czy nadal jesteś zainteresowany przedstawieniem go publiczności? :)

**Comment by erykpiast** [comment]
Skoro nie ma odpowiedzi, to na razie zamykam.
