### ISSUE TITLE
Pixel Pipeline w przeglądarkach

### ISSUE THREAD

**Issue by patrykziem** [meetjspl/poznan#4]
Chciałbym opowiedzieć jak wygląda proces renderowania elementów w przeglądarkach, czyli jak dopasowywane są style, obliczane pozycje, itd z zaznaczeniem, które etapy zajmują więcej czasu i jaki mamy na to wpływ jako programiści. 
Do tego przedstawiłbym jak można wykorzystać tę wiedzę w celu pisania wydajnych aplikacji, wyświetlanych w 60 fps. Warto byłoby wskazać jak unikać typowych wąskich gardeł jak wymuszanie synchronizacji layoutu (tzw Layout Trashing). Po prostu podstawy, które każdy powinien posiadać.

**Comment by erykpiast** [comment]
wow, brzmi obiecująco!

**Comment by Krakers** [comment]
+1, podoba mi się

**Comment by mbosek** [comment]
+1, extra

**Comment by kuba0506** [comment]
Brzmi interesująco, może wpadniesz też na meetjs do Warszawy?

**Comment by maciekpaprocki** [comment]
A moze dalbys zrodla to bym z checia w londynie poczytal :)

**Comment by patrykziem** [comment]
@kuba0506 Na ten moment, nie wiem jeszcze czy będę prezentował w poznaniu, bo to dopiero propozycja, która organizator musi zaakceptować. Z racji, że byłaby to moja pierwsza prezentacja na meet.js nie chciałbym zbyt wiele rzeczy na raz planować i skupić się najpierw na poznańskiej. Myślę, że jeśli odzew będzie pozytywny można taką opcję z pewnością rozważyć :)

@maciekpaprocki Jak tylko prezentacja będzie gotowa, mogę ją udostępnić. Źródła muszę najpierw uporządkować.

**Comment by naugtur** [comment]
Dobry temat, dawno nie było nic z tej dziedziny. Sprzedane ;)
Jakbyś potrzebował pogadać o tym jak się zmieścić w 25 minut albo jak dobrać proporcje materiału w prezentacji to pisz do mnie na maila, postaram się pomóc.

**Comment by naugtur** [comment]
Może wrócimy do tematu na wrzesień?

**Comment by patrykziem** [comment]
Myślę, że możemy wrócić :)

**Comment by naugtur** [comment]
Zwolniło mi się właśnie miejsce na 2 sierpnia, ale domyślam się że to za wcześnie :)

Jeśli potrzebujesz informacji to pytaj. Będę do Ciebie pisał jak wyklaruje się termin.

**Comment by patrykziem** [comment]
Wiem, wiem. Pisał do mnie Janek z pytaniem, czy go nie zastąpię, alę trochę za wcześnie jednak to jest :)

**Comment by patrykziem** [comment]
Dodaję link do prezentacji:

[http://slides.com/patrykziemkowski-1/deck-1](http://slides.com/patrykziemkowski-1/deck-1)

**Comment by erykpiast** [comment]
Super, dziękuję!

**Comment by SebastianPozoga** [comment]
Nagrania z prezentacji:
http://events.pozoga.eu/meet-js-32/
