### ISSUE TITLE
GraphQL & Apollo

### ISSUE THREAD

**Issue by Silhoue** [meetjspl/poznan#40]
Czym są, jak działają, jakie problemy rozwiązują i kiedy warto się nimi zainteresować.

**Comment by erykpiast** [comment]
Masz plan, żeby pokazać to z jakiś frameworkiem/libem do zarządzania stanem, czy zupełnie samodzielnie? Zastanawia mnie, jak to działa z jednej strony z global state (jak Redux), z drugiej z Obervablami.

**Comment by Silhoue** [comment]
Myślę, że dobrze byłoby pokazać jak to wpiąć do projektu - z jednej strony do źródła danych, a z drugiej do Reduxa (z Observablami raczej nie mam do czynienia). Czyli mniej o samych narzędziach, a więcej o ich użyciu.

**Comment by Silhoue** [comment]
Slajdy: https://github.com/Silhoue/talks/blob/master/GraphQL%20%26%20Apollo.pdf

**Comment by erykpiast** [comment]
Dziękuję za slajdy i raz jeszcze za prezentację! Zamykam issue :)
