### ISSUE TITLE
Mój rok w gamedevie

### ISSUE THREAD

**Issue by tiriana** [meetjspl/poznan#41]
Przez rok miałem okazję tworzyć gry HTML5, chciałbym podzielić się wiedzą o tym jak ten biznes wygląda od środka. 

Talk byłby trochę techniczny - powiedziałbym o bibliotekach w JS których używaliśmy. Bardziej skupiłbym się jednak na czymś bardziej ogólnym  - designie, architekturze, procesie, pracy na freelansie na remote. I na rzeczach które zrobiliśmy źle :-)

**Comment by erykpiast** [comment]
Super temat!

**Comment by tlakomy** [comment]
Słuchałbym!

**Comment by tiriana** [comment]
Jest jakiś ETA na następny meet.js? Temat i to o czym chcę opowiedzieć mam już ponotowane, ale muszę to jeszcze przekuć na jakieś przeźrocza (slajdy przyp. red.) i chciałbym wiedzieć jak bardzo spóźniony z tym już jestem.

**Comment by naugtur** [comment]
17 stycznia pending, ale nie wiem czy są jeszcze wolne miejsca na prelekcje.

**Comment by tiriana** [comment]
Ok. Mimo to ustawiam sobie deadline na 17 stycznia. Jeśli nie będzie wtedy
miejsc - mogę wykorzystać później.

2017-12-27 15:25 GMT+01:00 Zbyszek Tenerowicz <notifications@github.com>:

**Comment by tiriana** [comment]
[Radomir Wojtera - Mój rok w gamedevie.pdf](https://github.com/meetjspl/poznan/files/1777410/Radomir.Wojtera.-.Moj.rok.w.gamedevie.pdf)

**Comment by erykpiast** [comment]
Dzięki za slajdy i świetną prezentację!

**Comment by tiriana** [comment]
Jeszcze tylko mała autopromocja :) 
W czasie tworzenia talku wpadłem na pomysł zaimplementowania gry 23 zapałki na codewars. 

Tak jak wspomniałem - pierwszy gracz posiada algorytm wygrywający. Dlatego mój bot zawsze jest drugi, żeby dać szansę zwycięstwa. 

Jeśli ktoś ma ochotę się pobawić to zapraszam: https://www.codewars.com/kata/23-matches-or-more-dot-dot-dot/train/javascript

EOM.

**Comment by SebastianPozoga** [comment]
Nagrania są już dostępne:
http://events.pozoga.eu/meet-js-poznan-marzec-2018/
