### ISSUE TITLE
How to write good, composable 'pure' components in Angular 4+ (from the past React guy's perspective)

### ISSUE THREAD

**Issue by jtomaszewski** [meetjspl/poznan#43]
Based on my 1 year of experience building a huge SPA for www.tripsomnia.com/en/for-companies and my recent ~3 months of experience building another huge SPA for www.recruitee.com .

I could present it in January or February.

Some stuff I'd want to put in the talk (that's not the talk's plan yet; a few stuff might be added or removed, but it'll give u an idea what I want to talk about):

---

GOALS

A. if there's more than one way to do something, why is it like that? It's not art, it's engineering, there should be only one most valid option to do it.
  - Choose only one way to do each thing
  - If in some cases another way is better than the default one, then OK, we can allow to use both things, but then we must:
    - decide on clear rules when should a dev go with the way A and when with the way B

B. Code should be easy to understand, especially by new devs. They should be able to easily modify existing code without breaking things.

C. Avoid stupid bugs. Caused by: typos, change detection issues, styling issues, etc.

D. Performance where needed. If a view renders slowly, the lag is noticeable by users, there should be a quick and easy way to optimize it (without complicating the code at the same time).

---

STEPS

- ChangeDetectionStrategy.OnPush always!

- dont use cdRef.markForCheck

- use cdRef.detectChanges only when it is really needed (f.e. this component has received external async changes)

-  dont mutate inputs! 
    - work on temporary private variables
    - if something important changes, emit it up through outputs

- Avoid eventual ExpressionChangedAfterItHasBeenCheckedError :
    - never trigger any output events during the initialization or rendering of the component (that is: any of the lifecycle hooks)

- dont use async pipe

- tidy up html templates - decide on only one valid way of writing html elements and props

- reuse components - f.e. dont implement your own textarea input in your `MentionsInputComponent`, if you can use `TextareaComponent` instead 
    - if a component doesnt allow you to customize/do something - modify it with backwards compability (f.e. add a prop). please, try not to create a totally new component when you can extend the old one

- divide your components into small ones as much as you can
    - if a component is doing multiple separate things (f.e. a CandidatePageComponent is handling positioning of a AddCandidateModal which appears after clicking on a "Add candidate"; propably you could extract it to a separate component "AddCandidateButton", which handles opening the modal itself)

- when to use ng-content, and when to use TemplateRef?; Avoid using ContentChild for the sake of TemplateRef
    - why? TODO research / performance comparison examples

- If a component has too many logic and it seems like it has random `detectChanges()` lines put everywhere; then extract its logic from it:
    - to a separate component (and communicate with it via inputs and ouputs)
    - to a `@Self() @Host() ThatComponentController` service (and communicate with it via pub/sub)
    - to ngrx state and actions

- How to write wrapper components? ( https://www.dropbox.com/s/zdois9gqjqlfa8r/Screenshot%202017-11-29%2011.23.24.png?dl=0 )
    - unfortunately, in angular2 it's impossible to skip passing input prop in html template when its undefined ( https://www.dropbox.com/s/llje2w36ti57uc5/Screenshot%202017-11-29%2011.23.49.png?dl=0 )
    - so we could duplicate the default values in wrapper component as well ( https://www.dropbox.com/s/5ldyfnf1fevg344/Screenshot%202017-11-29%2011.24.22.png?dl=0 )
    - or BEST: we either need to extract the default value from the constructor to f.e. getter ( https://www.dropbox.com/s/vztgaaqwdi5dvpq/Screenshot%202017-11-29%2011.24.07.png?dl=0 , https://www.dropbox.com/s/k6k5jd2vgx75lam/Screenshot%202017-11-29%2011.24.34.png?dl=0 ). Result: https://www.dropbox.com/s/xp8fqnkty1zawuh/Screenshot%202017-11-29%2011.29.05.png?dl=0
    - or use custom decorator like `@WithDefaultValue('defaultValueProp')`
    - in summary: define all props of child component, but don't set its default values; and in the child implement fallback to default value when input is undefined

- Styles: sometimes we use @Input() prop, sometimes html attribute (`u-text-overflow`), sometimes css class (`.flex-grow`). Why so diverse?
   - prefix all css utilities classes / attributes with `u-` (`u-padding` `u-flex-grow` etc) - then we'll know it's just a css utility, not a component related class/prop
   - dont use html attributes for css, its bad, use classes instead
   - css utility classes are useful, yes, I wouldn't block them, but try to use props as much as possible
   - code examples
        - BEFORE: https://www.dropbox.com/s/1nhuxkwim0zcc4x/Screenshot%202017-11-30%2011.32.11.png?dl=0 ; AFTER: https://www.dropbox.com/s/3u8kaomds9cxv3j/Screenshot%202017-11-30%2011.33.53.png?dl=0

- Props namespacing: How do I know when the `[width]` prop is used by a directive (f.e. `DropdownDirective.width`) and when by the component (f.e. `SelectComponent.width`) ?
    - all directive props should be namespaced by the directive name (`[dropdown]` `[dropdownWidth]` `[dropdownMinWidth]`)
    - all component props shouldn't be namespaced (`[options]` `[width]` `[disabled]`)

- Use enums. Type stuff.

-  setup a linter so it disallows us to break those rules mentioned above

**Comment by erykpiast** [comment]
Jak myślisz, jak duża wiedza na temat angulara będzie wymagana, żeby zrozumieć prezentację? Konspekt wygląda super, ale przyznaję, że jako osoba, która ostatni raz miała styczność z tym frameworkiem w czasach v1.4, niewiele rozumiem :)

**Comment by jtomaszewski** [comment]
Raczej prezentacja będzie przydatna tylko dla osób, która coś robi obecnie w tym frameworku. 

Choć niektóre myślniki mogą dać domyślenia także innym, np. reactowcom (nie mutować rzeczy; dzielić componenty na mniejszy, typowanie rzeczy, etc).

Angular 1 a angular 2+ to dwa zupełnie różne światy, nic dziwnego, że niezbyt wiele Ci to wszystko mówi ;p

**Comment by oskarstrasburger** [comment]
Takich prelekcji właśnie mi brakuje. Sam też od roku tworzę duży projekt na Angularze, chętnie wymieniłbym się doświadczeniami.

**Comment by erykpiast** [comment]
Luźny pomysł: robimy teraz meetupy stricte pod React, jeżeli znalazłaby się osoba zainteresowana pociągnięciem tematu, zebraniem prelegentów mówiących o ng MOŻE moglibyśmy zacząć podobną serię eventów na temat tego frameworka.

To jest niestety problem z bardzo specjalistycznymi prezentacjami, że są potrzebne, ale nie ma gdzie ich przedstawić, żeby połowa widowni nie zasnęła :)

**Comment by tiriana** [comment]
istnieje grupa ng-poznań, ale ostatnio jest chyba mniej aktywna. Po liczbie
członków wnioskuję, że meet.js #angular mogłoby mieć wzięcie:
https://www.meetup.com/pl-PL/ng-poznan-meetup/members/

W dniu 4 grudnia 2017 15:14 użytkownik Eryk Napierała <
notifications@github.com> napisał:

**Comment by erykpiast** [comment]
W końcu, chciałoby się rzec (jeśli to cały czas ten sam temat). Dzięki za prezkę @jtomaszewski!
📼 https://www.youtube.com/watch?v=AiHcIlEDkx0
📖 http://jtom.me/talks/make-your-components-pure-and-dumb-and-composable.pdf
