### ISSUE TITLE
Programowanie funkcyjne w JS

### ISSUE THREAD

**Issue by diasle** [meetjspl/poznan#44]
Jak to wygląda z perspektywy osoby zaczynającej przygodę z programowaniem funkcyjnym, podstawowe pojęcia, zasady, wady i zalety... :)

**Comment by erykpiast** [comment]
Masz zamiar to pokazywać na przykładzie jakiejś konkretnej biblioteki?

**Comment by tlakomy** [comment]
Słuchałbym 👍

**Comment by erykpiast** [comment]
@diasle wielkie dzięki za fajną i przystępną prezentację! poproszę link do slajdów :)

**Comment by SebastianPozoga** [comment]
Nagrania z ostatniego spotkania już dostępne. 
http://events.pozoga.eu/meet-js-37/

**Comment by erykpiast** [comment]
@diasle ping! Podlinkujesz slajdy?

**Comment by erykpiast** [comment]
Zamykam bez slajdów. 🤷‍♀️

**Comment by tlakomy** [comment]
@naugtur moze podejdziesz do Diany, która siedzi w tym samym budynku i podpytasz o linka do slajdow? :p

**Comment by diasle** [comment]
Podsyłam linka do "back-upowej" wersji prezentacji https://docs.google.com/presentation/d/1MtYMj90SOv4vC2CqH8icQ2-2nIuANeHnEx_lHY65dWg/edit?usp=sharing  Przepraszam, że dopiero teraz
