### ISSUE TITLE
How i stopped worrying and learned to love vim

### ISSUE THREAD

**Issue by iansowinski** [meetjspl/poznan#45]
Może niewiele ma to wspólnego z JSem, ale myślę, że mógłbym za kilka miesięcy opowiedzieć o moich doświadczeniach z vimem, jego konfiguracją pod frontend oraz dlaczego jest taki wspaniały :)

**Comment by speedingdeer** [comment]
+1

**Comment by tlakomy** [comment]
Chętnie bym posłuchał, w JS wszystko zmienia się co 2 tygodnie, a vim wciąż jest taki sam

**Comment by erykpiast** [comment]
Emacs FTW!

**Comment by erykpiast** [comment]
Sory, nie ten guzik :D Super temat, tym bardziej, jeżeli podzielisz się configiem :)

**Comment by iansowinski** [comment]
Myślę, że można ten temat ugryźć na dwa sposoby: 

- Wprowadzenie do vima - czyli zachęcające przyszłych użytkowników podstawy, to co jest fajne w całej jego ergonomii i tak dalej.
- Config pod frontend/JS - czyli omówienie najfajniejszych wtyczek i ustawień i tego jak efektywnie korzystać z vima przy pisaniu javascriptowego kodu.

Nie mam za bardzo doświadczenia w prezkach, także chętnie przyjmę wszelką pomoc i sugestie :)

**Comment by erykpiast** [comment]
Ja bym chętniej posłuchał o konfiguracji, pierwszy punkt można zmieścić na jednym slajdzie ;) Z jakim edytorem/IDĘ będziesz porównywać? Z czym miałeś do tej pory styczność?

**Comment by iansowinski** [comment]
Głównie miałem do czynienia z sublimem, ale wiem, że wśród frontendowców atom jest chyba całkiem popularny.

**Comment by erykpiast** [comment]
Atom spoko, Visual Studio Code też ostatnio się wybił. Ale wiadomo, że masz jakiś własny punkt odniesienia :) Zastanawia mnie głównie podpowiadanie składni/instrumentacja kodu (i inne ficzery tzw. "intellisense") w takim Vimie, poddałem się konfigurując Emacs swego czasu :D

**Comment by speedingdeer** [comment]
Apropo Visual Studio Code to jest sporo materiałów jak sobie debugger podpiąć w różnych konfiguracjach z babel bez itd. Ale wiadomo vim rządzi :).

**Comment by iansowinski** [comment]
Na następnym nie dam rady niestety :/, ale myślę, że w styczniu mógłbym postarać się coś przygotować :)

**Comment by erykpiast** [comment]
W porządku! Postaram się dać znać z trochę większym wyprzedzeniem :)

**Comment by iansowinski** [comment]
... Chociaż po kilku miesiącach używam go raczej sporadycznie - to nie jest idealne oprogramowanie do pisania front-endu w 2018 roku, więc mogę o nim opowiedzieć jako o programie który fajnie uzupełnienia inne narzędzia o tym samym przeznaczeniu. Myślicie, że taka prezentacja miałaby sens?

**Comment by erykpiast** [comment]
To co, może dobry temat na meetup w styczniu? :)

**Comment by iansowinski** [comment]
Kiedy? :) 

Przysiądę przez święta i ogarnę :)

**Comment by iansowinski** [comment]
VIM: there and back again.

**Comment by erykpiast** [comment]
@iansowinski czy byłbyś chętny prezentować w połowie lutego?

**Comment by iansowinski** [comment]
@erympiast jest jakiś konkretny termin? Luty jest dla mnie wyjątkowo intensywny :(

**Comment by erykpiast** [comment]
Jest, 12 lutego.

**Comment by iansowinski** [comment]
Ech, ja odpadam póki co. Zamknę issue i otworzę jak trochę odetchnę i opracuję jakąś prezentację. Przepraszam, że tak, ale strasznie dużo spraw mi sie zwaliło w jednym momencie :(

**Comment by erykpiast** [comment]
Rozumiem, nie szkodzi!
