### ISSUE TITLE
Co siedzi pod maską? czyli jak działają silniki Java Script

### ISSUE THREAD

**Issue by DzikowskiW** [meetjspl/poznan#46]
Dzięki za ciepłe przyjęcie na piątkowym meet.js. Załączam slajdy z mojej prezentacji o działaniu silników JS:

[Wojciech Dzikowski - Jak działają silniki JS.pdf](https://github.com/meetjspl/poznan/files/1788085/Wojciech.Dzikowski.-.Jak.dzialaja.silniki.JS.pdf)

**Comment by erykpiast** [comment]
Dzięki za super prezentację, @DzikowskiW!

**Comment by tiriana** [comment]
@erykpiast Jest może jakieś ETA nagrań? Chciałbym rozesłać tę prezkę kliku osobom.

**Comment by erykpiast** [comment]
[@SebastianPozoga](https://github.com/SebastianPozoga) się tym zajmuje, myślę, że wrzuci lada dzień :)

**Comment by SebastianPozoga** [comment]
Nagrania są już dostępne:
http://events.pozoga.eu/meet-js-poznan-marzec-2018/
