### ISSUE TITLE
Beyond Polymer - current state of web components. Are we getting closer to the end of Framework Churn?

### ISSUE THREAD

**Issue by khola** [meetjspl/poznan#48]
Ostatnio udało mi się popracować trochę z WC przy okazji kilku mniejszych projektów, więc chętnie opowiem trochę o samej idei WC i stanie tej "technologii" "na dziś". 

Plan prelekcji widziałbym +/- tak:

## 1. What are Web Components anyway?

1. Definition & idea - few words about creating reusable, framework agnostic elements that work everywhere.
2. Brief History
3. Technologies involved
* Shadow DOM
* Custom Elements
* HTML Templates
* HTML Imports

## 2. Libraries to work with WC

_Few words about implementation details of each library, history etc._

1. Polymer
2. Skate.js
3. Stencil.js
4. X-tag

## 3. Very basic component made with Polymer and Stencil.js

_Show different approaches to development and deployment of WC._

## 5. Is the era of Framework Churn really coming to an end?

_Sum up - current state and few thoughts about future._

**Comment by erykpiast** [comment]
Fajny pomysł na prezentację! Chciałbyś przedstawić ją na najbliższym mettupie (pod koniec kwietnia)?

**Comment by khola** [comment]
Jasne, bardzo chętnie :)

**Comment by erykpiast** [comment]
Super! Planujesz jakiś live coding, czy wcześniej przygotowane przykłady?

**Comment by khola** [comment]
Wcześniej przygotowane przykłady :)

**Comment by erykpiast** [comment]
Idealnie! Powiesz coś o wydajnościowym aspekcie tych rozwiązań? :)

**Comment by khola** [comment]
W sumie nie myślałem o tym - fajny pomysł, chętnie dodam to do planu - zwłaszcza że Stencil potrafi być bardzo konkurencyjny jeśli chodzi o ilość serwowanych kb.

**Comment by SebastianPozoga** [comment]
nagrania: https://youtu.be/G9WNZ2T9lyk

**Comment by erykpiast** [comment]
Dzięki @SebastianPozoga! Dorzucisz proszę slajdy, @khola?

**Comment by khola** [comment]
https://goo.gl/eB9RRg proszę :)

**Comment by erykpiast** [comment]
Świetnie, dziękuję!
