### ISSUE TITLE
Redux subapps: as a solution for dealing with large scale/team apps.

### ISSUE THREAD

**Issue by radosny** [meetjspl/poznan#49]
1. Redux subapp
- przedstawienie konceptu
- dlaczego zdecydowalismy się na to podejscie
2. Concept vs. real life
- multi-package repo
- subapp == package == store
- plusy i minusy na przykładzie wdrożonej aplikacji
3. Demo time - przykładowa prosta appka w React + Redux pokazująca koncept

Jeżeli chodzi o terminy to pasowałoby mi najwcześniej pod koniec Kwietnia (po 23)

**Comment by kalek** [comment]
+1

**Comment by speedingdeer** [comment]
haha dokładnie tak robiłem i nie wiedziałem, że to ma nazwę :) teraz wygooglałem dopiero.
+1

**Comment by SebastianPozoga** [comment]
Nagrania

- Radosław Małecki - "Redux subapps: as a solution for dealing with large scale/team apps"
https://youtu.be/WU4iYA1gqbM

**Comment by erykpiast** [comment]
@radosny, mógłbyś załączyć slajdy? zamknę wtedy issue.

**Comment by radosny** [comment]
Jasne!
https://radosny.github.io/redux-subapp

**Comment by erykpiast** [comment]
Dzięki!
