### ISSUE TITLE
Large Scale Applications built with Typed JavaScript Extension & Full-Featured IDE.

### ISSUE THREAD

**Issue by yoosiba** [meetjspl/poznan#5]
Cześć.

Czy w JS można pisać nie trywialne aplikacje biznesowe? Odpowiedź brzmi "Tak". A dokładniej "Tak, da się". Cały szkopuł w tym "da się". A gdyby odpowiedź brzmiała "Tak, to takie proste."?
Coraz lepsze narzędzia, coraz więcej bibliotek, nowe standardy języka (ES6, ES7) - to wszystko razem sprawia, że praca z JS jest coraz przyjemniejsza.
Oczywiście są ludzie dla których to za mało, w efekcie dużo języków jest kompilowanych do JS.
Są również podejścia mniej radykalne, w których posługujemy się nadzbiorem JS. Dzięki temu mamy wszystko to, co oferuje JS, ale dostajemy również cały zestaw nowych funkcjonalności.

W mojej prezentacji przedstawię przykład nadzbioru języka JS wraz z dedykowanym IDE.

**Comment by erykpiast** [comment]
Brzmi ciekawie. Udostępniacie to gdzieś już?

**Comment by yoosiba** [comment]
Na koniec prezentacji będę o tym mówił, ale tak na szybko:

Jeszcze nie. Natomiast od samego początku założenie było takie, że całość będzie dostępna (za darmo) dla wszystkich. Jednak sposób w jaki chcemy to zrealizować nie jest jeszcze jasny. 
Dodatkowo, udostępniając to dla wszystkich, powinniśmy spełniać pewne oczekiwania odbiorców, tylko co by to było? Wsparcie dla AngularJS? Grunt/Gulp? TypeScript? ... 
Obecnie szukamy osób zainteresowanych współpracą i użyciem tego we własnych projektach, takich 'early adopters' z którymi moglibyśmy ukształtować całość w narzędzie spełniające oczekiwanie szerszej publiczności.

**Comment by erykpiast** [comment]
Chyba nie ma lepszego sposobu na pracę koncepcyjną niż rozpoczęcie dyskusji na forum open source :) No ale to offtop. Czekam z niecierpliwością na prezentację!

**Comment by naugtur** [comment]
Dzięki! Wrzuć link do prezentacji jeśli jest online

**Comment by yoosiba** [comment]
Właśnie sprawdziłem, jak długo mówiłem. 
Przepraszam organizatorów, gratuluje (wytrwałości) uczestnikom :smirk:
Linki, jak tylko będą dostępne, dorzucę do tego issue.

**Comment by naugtur** [comment]
Jak idzie z linkami? ;)

**Comment by naugtur** [comment]
zamykam, ale jeszcze się będę upominał

**Comment by yoosiba** [comment]
Dzięki za możliwość prezentacji, a jednocześnie przepraszam za brak slajdów. 
Z drugiej strony jest coś lepszego. Otóż zapraszam wszystkich do wypróbowania IDE oraz samego języka!
Od dziś całość jest dostępna do uzytku : http://numberfour.github.io/n4js/
Dodatkowo, zainteresowani mogą sami zanurkować w kod źródłowy: https://github.com/NumberFour/n4js/

Proszę dzielić się wrażeniami przez powyższe linki, lub bezpośrednio do mnie!

**Comment by SebastianPozoga** [comment]
Nagrania dostępne na:
http://events.pozoga.eu/meet-js-poznan-10-2015/
