### ISSUE TITLE
glimmer.js internals

### ISSUE THREAD

**Issue by adrianmroz** [meetjspl/poznan#50]
Musiałem ostatnio ocenić kilka frameworków/bibliotek do nowej aplikacji i nauczyłem się sporo o działaniu glimmera. 

Opowiedziałbym w jaki sposób pod spodem śledzi zmiany modeli i jak zrealizowano renderowanie oraz jakie daje to plusy i dodatkowe funkcje. 

Na początek oczywiście wstęp do glimmera na jednym slajdzie (dużo więcej tam nie ma). 

Czyli pod pozorem frameworka będę opowiadał o wirtualnych maszynach i konstruowaniu sztucznego czasu!

PS. Będę ostro porównywał po drodze do Reacta.

**Comment by tiriana** [comment]
Brzmi spoko

Sob., 21.04.2018, 21:33 użytkownik Adrian Mróź <notifications@github.com>
napisał:

**Comment by tlakomy** [comment]
Słuchałbym!

**Comment by adrianmroz** [comment]
[deck.pdf](https://github.com/meetjspl/poznan/files/2687596/deck.pdf)

**Comment by erykpiast** [comment]
Dzięki za porywającą przemowę!
