### ISSUE TITLE
micro-frontends

### ISSUE THREAD

**Issue by przemuh** [meetjspl/poznan#51]
Mikroserwisy w świecie front-endu ;) Czyli jak pogodzić angulara, reacta, embera, vue ... w jednej aplikacji :) 

- koncept
- przykład
- zalety / pułapki / wady

**Comment by erykpiast** [comment]
To ciekawy temat, sam się zmagam z taką architekturą :) Rozumiem, że będziesz przedstawiał przypadek Egnyte?

**Comment by przemuh** [comment]
Done by Jakub Hola :) on meetjs summit.
