### ISSUE TITLE
Firebase JS API with React

### ISSUE THREAD

**Issue by tomekkonieczny** [meetjspl/poznan#53]
Pełne case study użycia Firebase do projektu React: hosting, baza danych (db, firestore), auth, storage, REST API. W skrócie: jak stworzyć pełną aplikację bez żadnych ograniczeń korzystając z wszystkich możliwości Firebase.

**Comment by erykpiast** [comment]
@tomekkonieczny nie wiem, czy temat jeszcze aktualny, 6 miesięcy to jednak dekada w świecie JS, ale zaryzykuję: czy chciałbyś zaprezentować temat na najbliższym spotkaniu, 14 grudnia?

**Comment by erykpiast** [comment]
Skoro cisza, to zamykam. Jeżeli jednak chciałbyś zaprezentować ten temat, daj znać!
