### ISSUE TITLE
Przygody ze ścieżkowaniem czyli react-router@4.2.0

### ISSUE THREAD

**Issue by pozytron** [meetjspl/poznan#54]
Case study prostej aplikacji z routingiem w React plus omówienie zmiany w react-router między @3.2.1 a @4.2.0. Live coding - jak bogowie demo pozwolą ;p

**Comment by erykpiast** [comment]
Z live codingiem bym uważał. Najlepiej trochę oszukać i przygotować sobie wcześniej checkpointy (np. jako commity w repo), które będziesz mógł załadować w danym momencie i mieć pewność, że wszystko działa :)

Nie mam dużego doświadczenia z React Routerem, zastanawiam się, jak duża wiedza na temat tej biblioteki będzie potrzebna do zrozumienia prezentacji?

**Comment by pozytron** [comment]
@erykpiast dzięki za uwagę,
co do wiedzy, to jest to na tyle prosty temat do wprowadzenia, że po prostu poświęcę chwilę na to żeby wprowadzić wszystkich w temat :)

**Comment by pozytron** [comment]
prezka tutaj:
https://slides.com/michaltymula/meetjsreactrouter/#/
repo do prezki tu:
https://github.com/pozytron/react-router-v4-playground
