### ISSUE TITLE
Navigating the hype-driven frontend development world without going insane

### ISSUE THREAD

**Issue by kitze** [meetjspl/poznan#55]
The obsession to always move on to the latest and greatest, and the fear of missing out while working with something that's older than few months is currently dominating the dev world. In my previous talks, I always included a short bit about this topic, and it resonated well with the audience. This time, I want to do a full talk on it, because I think everyone is struggling with this problem.

**Comment by khola** [comment]
Sounds great!

**Comment by przemuh** [comment]
Is it still valid ? :)

https://www.youtube.com/watch?v=_kVxXV0TQ7M&t=1s

https://www.youtube.com/watch?v=QZ6aC6G0ufg

https://www.youtube.com/watch?v=E-TRB28KMMQ

https://www.youtube.com/watch?v=R_2q5LZzF9M
