### ISSUE TITLE
What I learned creating my first Open Source library

### ISSUE THREAD

**Issue by maciejmyslinski** [meetjspl/poznan#57]
Tę prezkę przedstawiłem już w Poznaniu [na chill.js](
https://web.facebook.com/events/1860612420656129/permalink/1868374533213251/) i przyjęła się świetnie, dlatego podbijam świat dalej 😉😉

**Pitch prezki:**

*PL*
Zawsze marzyłem o stworzeniu swojej własnej biblioteki Open-Source. Nigdy nie brakowało mi też wymówek: muszę zdobyć więcej doświadczenia, jest tyle innych pilnych obowiązków, są lepsi ode mnie. Poza tym wydawało się, że każdy istotny problem został już rozwiązany. Założę się, że jesteś choć trochę podobny do mnie.
Z mojej prezentacji dowiesz się:
* jak zauważyłem problem, który nie został jeszcze rozwiązany,
* jak wypracowałem rozwiązanie,
* czego nauczyłem się po drodze.

No i będziesz o krok bliżej stworzenia swojej własnej biblioteki Open-Source!

*EN*
I always dreamed about creating my own Open-Source library. I always had a lot of excuses, too: I'm not experienced yet, I don't have enough time, I don't have an idea. I bet you are a little bit like me.
From this presentation you'll learn:
* how I noticed a problem that wasn't yet solved
* what lead me to the solution
* what I learned along the way

And you may be one step closer to creating your own open-source project one day!

Chętnie wbiję w najbliższy wolny termin, jestem też deską ratunku w razie gdyby ktoś z prelegentów w ostatniej chwili nie mógł wystąpić 🙂

**Comment by maciejmyslinski** [comment]
Howdy @naugtur! Zgaduję, że nie miałeś jeszcze okazji zastanowić się nad moją propozycją. Organizowanie meetupów to pewnie sporo pracy.
Jakie wolne terminy masz jeszcze na meet.js Poznań?

**Comment by tlakomy** [comment]
Cześć!

Aktualnie jesteśmy skupieni na organizacji meet.js summit i do tego czasu prawdopodobnie nie będzie meet.js, ale może zgłosisz tą prezentację na summit? :)

**Comment by maciejmyslinski** [comment]
@tlakomy Dzięki za insight, tak zrobię 👍🙂

**Comment by erykpiast** [comment]
@maciejmyslinski czy chciałbyś zaprezentować temat na najbliższym spotkaniu, 14 grudnia?

**Comment by erykpiast** [comment]
@maciejmyslinski też brzmi ciekawie! Dodasz issue z abstraktem?

**Comment by maciejmyslinski** [comment]
jasne 👍

**Comment by maciejmyslinski** [comment]
@erykpiast zobacz #58

**Comment by erykpiast** [comment]
@maciejmyslinski No dobrze, to co z tą prezentacją? :) Będziesz chciał pokazywać ją jeszcze w Poznaniu? Na przykład w styczniu lub w lutym? Ja nadal z chęcią bym posłuchał!

**Comment by erykpiast** [comment]
@maciejmyslinski czy byłbyś chętny prezentować w połowie lutego?

**Comment by maciejmyslinski** [comment]
@erykpiast myślę, że już się wyczerpałem w tym temacie 😉
