### ISSUE TITLE
cypress.io i testy e2e

### ISSUE THREAD

**Issue by przemyslawjanpietrzak** [meetjspl/poznan#59]
Mógłbym opowiedzieć o testach e2e: jak je pisać, na co uważać i dlaczego warto. Pokazać możliwości cypressa, porównać go do selenium i wytłumaczyć jak szpiegować API z jego poziomu. A na koniec parę bashowo/dockerowych sztuczek które pozwolą łatwo wpiąć cypressa do CI.

**Comment by erykpiast** [comment]
Słyszałem, że prezentacja była zacna! Poproszę slajdy.

**Comment by przemyslawjanpietrzak** [comment]
Slajdy: https://przemyslawjanpietrzak.github.io/przemyslawjanpietrzak.github.io/cypress/presentation.pdf

**Comment by erykpiast** [comment]
Dziękuję!
