### ISSUE TITLE
Desktopowy JavaScript z Electronem: zbuduj swoje IDE

### ISSUE THREAD

**Issue by mjaniszew** [meetjspl/poznan#6]
Prędzej czy później to musiało się stać. Electron dosyć sukcesywnie ostatnimi czasy wgryza się w rynek i juz teraz można znaleźć sporo aplikacji napisanych za jego pomocą: Atom, Slack, Visual Studio Code czy Kitematic.

Chciałbym porozmawiać chwilę o swoich dotychczasowych doświadczeniach związanych z Electronem, a także pokazać jak szybko można za jego pomocą zbudować aplikacje np. swoje własne IDE (bo przecież potrzebujemy jeszcze więcej edytorów!). Jak starczy czasu, to także wraz z procesem dystrybucji aplikacji itd.

Prezentacji jeszcze nie mam i zbyt dużo w sumie to jej nie będzie, głównie live coding. Nie wiem ile czasowo całość zajmie, część materiałów mam gotowych i musiałbym sprawdzić głównie ile cały live coding zajmie, o ile ktoś będzie oczywiście tematem zainteresowany.

**Comment by Krakers** [comment]
:+1:

**Comment by naugtur** [comment]
Dobry temat.
Mogę Ci pomóc tak zorganizować livecoding, żeby uniknąć paru pułapek.
Odezwij sie na maila naugtur@gmail.com

**Comment by erykpiast** [comment]
Jeej, super! Chętnie posłucham Ale fakt, jeśli live coding, to trzeba dobrze ogarnąć.

**Comment by mjaniszew** [comment]
Jasne, jak będę miał chwilę to skrobnę później maila i opiszę co aktualnie mam, co planuje itd. Parę porad na pewno się przyda, dzięki.

**Comment by naugtur** [comment]
podlinkuj materiały i zamykam

**Comment by mjaniszew** [comment]
Prezentacja z linkami do materiałów: https://docs.google.com/presentation/d/1TFDF2vycYVHzHiLkKG2452se4o7O-qMePksYMWxn1G8/edit?usp=sharing

**Comment by SebastianPozoga** [comment]
Prezentacja dostępna na:
http://events.pozoga.eu/meet-js-marzec-2016/
