### ISSUE TITLE
React Native z Perspektywy Front-Endu

### ISSUE THREAD

**Issue by lebrande** [meetjspl/poznan#60]
Widziałem, że były już 3 prezentacje nt. React Native, ostatnia w 2017.
Nie byłem na nich, ale sprawdzę, na tyle na ile to możliwe co już było, jakie tematy były poruszane itd.
Przyznaję, że nie mam za sobą żadnych komercyjnych projektów aplikacji mobilnych, a sam React Native traktuję jako projekt po godzinach.
Ale właśnie o tym chciałbym opowiedzieć, co mnie zaskoczyło, z czym przyszło mi się zmierzyć w swojej pierwszej aplikacji jako fron-end kolesiowi. 

## Konspekt
- State of React Native - 2019
- Czy da się pisać aplikacje mobile tylko z JS bez doświadczenia w aplikacjach mobilnych?
- Kiedy RN będzie dobrym rozwiązaniem a kiedy kiepskim?
- React Native z perspektywy front-end developera
- Z jakimi problemami (nowymi rzeczami) nieznanymi w w font-endzie musiałem się zapoznać.
- Jak zacząć ze swój pierwszy projekt i szybko zaprezentować/zobaczyć efekty.

## Wątpliwości
Lepiej, żeby temat wprowadzał w React Native czy skupić się na bardziej zaawansowanych problemach?

**Comment by lebrande** [comment]
Chciałbym przypiąć labelki ale nie widzę dostępnej tej opcji 😄

**Comment by erykpiast** [comment]
Chyba tylko ja mogę :D 💃 

Jeżeli będzie więcej o Twoich "przygodach" i problemach niż o kodzie, to z chęcią posłucham :) W sensie, fajnie gdyby nie była to kolejna prezentacja z serii "How to bootstrap a project in XYZ framework" :D

**Comment by lebrande** [comment]
Tak, mam trochę przygód, i zamierzam ubrać to w konkretną historię:
- Wrażenia z konferencji React Native EU 2018, jak wygląda społeczność RN
- Jak developerzy aplikacji mobilnych postrzegają React Native. Dużo osób w Intive w Poznaniu (tu pracuję) to iOS i Android.
- Jak React Native ma się teraz do innych rozwiązań np. hybrydy, Flutter, Native Script.
- Chciałbym się skupić na tym co faktycznie możemy zrobić z RN znając tylko JavaScript, jak osiągnąć przewagę, gdzie lepiej się nie pchać bez doświadczenia w mobile.
- Zakładam, że kod Reacta wszyscy widzieli 🤓nie zamierzam skupiać się na kodzie.

**Comment by erykpiast** [comment]
Hej! Chciałbyś przedstawić temat na najbliższym spotkaniu, 12 kwietnia?

**Comment by erykpiast** [comment]
Ping! Wracam z pytaniem, tym razem odnośnie daty 21 maja :)

**Comment by lebrande** [comment]
Hej @erykpiast, wybacz brak odpowiedzi.
Co do pytania o 21 maja: dasz mi czas na odpowiedź do jutra?

**Comment by erykpiast** [comment]
Oczywiście! :)

**Comment by lebrande** [comment]
Biorę to 😉 Skontaktuje się z Tobą @erykpiast W pewnej sprawie, chodzi o niespodziankę. Hej!

**Comment by erykpiast** [comment]
Już się boję :D

**Comment by erykpiast** [comment]
@lebrande dzięki za wystąpienie! Wrzucisz link do slajdów? :)
Ja zostawiam wideo: https://www.youtube.com/watch?v=bUp6reDqdoM
