### ISSUE TITLE
React Recompose - Higher Order Components Everywhere!

### ISSUE THREAD

**Issue by lebrande** [meetjspl/poznan#61]
Niedawno stałem się wielkim fanem biblioteki [recompose](https://github.com/acdlite/recompose).
Jest to narzędzie dedykowane Reactowi. Będzie o wzorcach programowania funkcyjnego w JS, higher order componentach i jak nie wpaść w pewne pułapki tworząc kod z recompose.
Recompose używam na codzień w komercyjnym projekcie.
Temat wydaje mi się zaawansowany, dlatego postaram się wyjaśnić czym w ogóle jest ta biblioteka i jak ją zrozumieć, jak przestawić się na myślenie w higher order componentach.

Nie zamierzam robić live codingu, ale będę pokazywał snipety i postaram się wszystko odpowiednio animować, aby wzrokowcy mogli odnieść bardzo pozytywne wrażenia.

## Konspekt
- W czym pomoże recompose?
- Refactoring gotowego komponentu, zaczynamy od konkretów
- Recompose i dev tools. Problem zagnieżdżeń.
- Jak działa funkcja compose? Wzorzec pipe (jak to po polsku?)
- Recompose a Higher Order Components
- Currying jako element kompozycji,
- Kiedy i jak tworzyć własne higher order components?

**Comment by lebrande** [comment]
EN version

Recently I've became a huge fan of [recompose](https://github.com/acdlite/recompose).
That's a tool for React, which helps you write code with approach focused on higher order components.
I will show you some JS design patterns.
Also I will give you tips based on my experience.

I going to speak in Polish ;(

## Plan
- How does recompose help you make your code better and get pro skills :)
- Refactoring of already created component.
- Recompose and dev tools. Nesting issue.
- How does `compose` function work? Pipe pattern.
- Higher Order Component role in `recompose`
- Currying as a required part of recompose.
- Reasons for creating your own higher order components.

**Comment by erykpiast** [comment]
Zawsze mnie zastanawiało, czy ktoś kiedyś pokusił się o one-shot refaktor dużej apki z użyciem `recompose` i może porównać rozmiar bundle przed i po. Mam tu na myśli głównie rozwlekłość definicji klas w JS (szczególnie po transpilacji do ES5) i współdzielenie kodu. Czyli ile komponentów wystarczy przepisać z `class` na `useState` żeby koszt dodania zależności do projektu się zniwelował :P

**Comment by lebrande** [comment]
Dobry punkt. Nie sądzę, aby udało mi się dokonać porównania na dużej apce, ponieważ piszemy od razu z `recompose`. Sam pomysł porównania bundle przed i po wydaje się interesujący.

**Comment by naugtur** [comment]
Super temat. Recompose nie jest nowym gadżetem o którym wszyscy chcą mówić (hooks) a zasługuje na dużo większa popularność.
Masz ode mnie dodatkowe 10 minut na prelekcję jeśli chcesz 😅

**Comment by przemuh** [comment]
Słuchałbym :)

**Comment by lebrande** [comment]
@naugtur @przemuh dzięki, za feedback  👍 
Bardzo fajnie to czytać. Chętnie się rozgadam 😂

**Comment by lebrande** [comment]
Udostepniam prezkè: http://recompose-hocs-everywhere.surge.sh/#/components-streams-cover

**Comment by SebastianPozoga** [comment]
Nagrania: https://www.youtube.com/watch?v=EAeVlkIGKag&feature=youtu.be

**Comment by lebrande** [comment]
@SebastianPozoga dzięki za nagranie wideo :)
@naugtur zapomniałem włączyć stopera i nawet nie wiem jak upłynęło 37 min. Przepraszam, że nadużyłem dodatkowego czasu :)

**Comment by erykpiast** [comment]
Wielkie dzięki za prezentację! Była 👌
