### ISSUE TITLE
Subiektywny przegląd sytuacji na froncie (2019)

### ISSUE THREAD

**Issue by mat3e** [meetjspl/poznan#62]
"Nowy dzień, nowy framework". Jak żyć? 

Jestem jedną z osób, śledzących front-endy i pragnę podzielić się swoimi obserwacjami. Zarówno mający na ten temat swoje własne przemyślenia jak i oczekujący "pigułki", dającej im pewien ogląd sytuacji, powinni znaleźć tutaj coś dla siebie. 

Jacy są główni gracze, jeśli chodzi o front-end? Co jest bardziej popularne? React? Vue? Czy jest jakaś nadzieja na wspólny kod, niezależnie od użytych frameworków? Jakie są trendy i przyszłość JS-a? Czego możemy się spodziewać w 2019 roku? Na te i inne pytania postaram się odpowiedzieć w rozrywkowej formie.

**Comment by mat3e** [comment]
Na koniec poprzedniego roku mówiłem o tym zarówno w formie 5-minutowego lighting talka, jak i w formie dłuższego wystąpienia/wykładu (75 minut): https://youtu.be/KDTP9Dfkh1Q.

Na meet.js Poznań przygotowałbym wersję: mniej o historii, więcej o przyszłości (np. z raportu npm-a). Do tego Chromium, Web Componenty, 3factor app.

**Comment by naugtur** [comment]
Proponowałbym dorzucić parę słów o decyzji MSFT żeby Edge oprzeć na Chromium i konsekwencjach dla ekosystemu.

Po takiej prelekcji możn zostawić slot na otwartą dyskusję dla wszystkich,

**Comment by mat3e** [comment]
Dokładnie. Wspomniałem o tym _Chromium_ właśnie z myślą o Edge'u :)

**Comment by mat3e** [comment]
No to slajdy: https://mat3e.github.io/talks/fe-overview/meetjs-pzn.html

**Comment by SebastianPozoga** [comment]
Nagrania: https://youtu.be/Aybh_2pIi2I

**Comment by mat3e** [comment]
> Nagrania: https://youtu.be/Aybh_2pIi2I

Super! Ekspresowe tempo 👍

Niestety, mam jednak nazwisko podatne na błędy i w opisie na YouTube wkradła się literówka. Chrzonstkowski powinno być bez pierwszego "k", po prostu "Chrzonstowski" 😄

**Comment by SebastianPozoga** [comment]
Poprawione. Btw. Kiedy coś kopiujesz 1:1 i dalej jest nie tak... Brałem z https://www.facebook.com/events/144669406438581/?active_tab=about

@erykpiast Możecie poprawić ;-)

Normalnie ściągasz na sprawdzianie od kolegi w ławce i dalej masz źle....

**Comment by erykpiast** [comment]
😱 @mat3e, kto to widział, takie trudne nazwisko. Wybacz! Poza tym, dzięki za prezentację. Mateusz bawi i uczy ;)

**Comment by bigsergey** [comment]
@mat3e fajna prezentacja!
