### ISSUE TITLE
Never write another HOC! ;)

### ISSUE THREAD

**Issue by kamilkoterba** [meetjspl/poznan#63]
Każdy Higher order component da się przepisać na Render Prop pattern. Na necie można znaleźć same superlatywy i wygląda na to, że to całkiem uniwersalny pattern. Do tego ma kilka drobnych zalet ponad HOC więc potencjalnie jest lepszym domyślnym wyborem.

Moim głównym celem jest pokazanie jak napisać prosty HOC i Render Prop i jak przepisać jeden na drugi. Zależy mi by po tej prelekcji uczestnicy rozumieli jak napisać HOCa lub Render Prop. 

Tytuł jest zaczepny i ma na celu zwrócenie uwagi, ale na pewno nie zamierzam hejtować HOCa, co wyjaśniam na początku prezentacji. Jest też referencją do [dyskusji rozpoczętej przez Michaela Jacksona](https://twitter.com/mjackson/status/885910553432018945?lang=en) 

# Konspekt
* Odłonięcie prawdziwego tytułu - Benefits of using render prop pattern
* Referencja do zasady SOLID
* Jak napisać prosty HOC
* Jak napisać prosty Render Prop
* Jak rozszerzyć HOC o kolejną odpowiedzialność (zagnieżdzanie HOCów)
* Jak rozszerzyć Render Prop o kolejną odpowiedzialność (zagnieżdzanie Render Propów)
* Podsumowanie zalet i wad
* Wskazanie na dodatkową wartość porządkującą jaką do HOCa wprowadza recompose jako zapowiedź prelekcji #61 

Szacowany czas do 45 min

**Comment by kamilkoterba** [comment]
Hej, zależy mi żeby mówić na początku bo jestem ograniczony czasowo. Myślę, że mogę zrobić ogólne wprowadzenie do HOC i Render Prop pokazać zalety Render Prop i na koniec wspomnieć coś o Recompose jako zapowiedź Twojej prelekcji. Więc po tym ludzie powinni już kumać jak wygląda podstawowy HOC.

**Comment by piotros** [comment]
Panowie czy jest szansa na wrzucenie na YouTube nagrania z tej prelekcji? Zapowiada się bardzo ciekawie ;)

**Comment by kamilkoterba** [comment]
Nie mam nic przeciwko. @naugtur nagrywamy to?

**Comment by przemuh** [comment]
Jeśli przyjdzie Sebastian to będzie na: https://events.pozoga.eu/

Z kalendarza wynika, że przyjdzie ;)

**Comment by SebastianPozoga** [comment]
będę ;-)

**Comment by SebastianPozoga** [comment]
No i są nagrania: https://youtu.be/3MfRwWYt12s
;-)

**Comment by piotros** [comment]
Dzięki wielkie ;)

**Comment by erykpiast** [comment]
@piotros fajna prezka, dzięki! Wrzucisz slajdy?

**Comment by piotros** [comment]
@erykpiast wołaj raczej @kamilkoterba ;)

**Comment by erykpiast** [comment]
🤦🏾‍♀️

**Comment by kamilkoterba** [comment]
Slajdy https://docs.google.com/presentation/d/1_t82BjoS6oqgpoO7XpTNvV4Sj4hREYZsrSE-TSCvQPk/edit?usp=sharing
@SebastianPozoga Możesz podlinkować w opisie video?

**Comment by erykpiast** [comment]
Z tego co widzę, jest wyżej :) Dzięki, zamykam issue.

**Comment by SebastianPozoga** [comment]
@kamilkoterba done ;-)
