### ISSUE TITLE
Dashboard dla developera (mozaik)

### ISSUE THREAD

**Issue by przemuh** [meetjspl/poznan#64]
Ostatnio pracowałem nad postawieniem takiego informacyjnego dashboardu u nas w firmie.

Chodziło o wykorzystanie telewizora dostępnego na open space, tak aby wyświetlać na nim różne statusy np.:

- status build'a z jenkins/CI
- status środowisk (qa, stage, production) up/down, która wersja
- liczbę tasków z jiry np. eskalacje, rzeczy w in-progress / ready to be test
- listę merge requestów z gitlaba

Mógłbym opowiedzieć o: 
- motywacji do zbudowania takiego narzędzia
- jakie są dostępne narzędzia i dlaczego wybrałem akurat [mozaik.rocks](http://mozaik.rocks)
- jaka jest architektura mozaik i jak pisać do niego własne rozszerzenia
- jak dzięki temu udało mi się dorzucić swoją cegiełkę do open source :)

Dajcie znać czy temat wydaje się interesujący.
Poniżej kilka screenów z naszego dashboarda (dane celowo zmienione ;) RODO :D):

![image](https://user-images.githubusercontent.com/3865478/52775415-f4399c80-303f-11e9-9731-d75fa6534814.png)

![image](https://user-images.githubusercontent.com/3865478/52775669-7de96a00-3040-11e9-9a8d-607a591103e9.png)

A tutaj screeny z demo mozaik:

![image](https://user-images.githubusercontent.com/3865478/52775711-99547500-3040-11e9-86bb-14d216ca0fc6.png)

**Comment by erykpiast** [comment]
Fajna sprawa! Czy najbliższy meet.js, 12 kwietnia, wchodzi w grę?

**Comment by przemuh** [comment]
Może być :) myślę, że się wyrobię.

**Comment by tomasztomys** [comment]
@przemuh ile czasu zajęło stworzenie takiego dashboardu?

**Comment by przemuh** [comment]
@tomasztomys Samo postawienie i skorzystanie z gotowych pluginów można zrobić w jeden dzień. W naszym przypadku potrzebowaliśmy customowych integracji z różnymi serwisami. Pracowałem nad tym równolegle z innymi zadaniami w sprincie. Całośc zamknęła się w jednym 2 tygodniowym sprincie :) ...ale myślę, że można to zrobić o wiele szybciej :) W tym czasie napisałem własne integracje wraz z widgetami do:

- internalowego serwisu monitorującego
- jiry
- gitlaba
- jenkinsa

**Comment by przemuh** [comment]
Slajdy: https://slides.com/przemuh/mozaikrocks/#/

Nagrania niestety nie było...ale zapraszam do obserwowania przemuh.pl - wrzucę tam niebawem posta na temat mozaik.

**Comment by erykpiast** [comment]
Wielkie dzięki! Świetna prezentacja :)
