### ISSUE TITLE
The Story of CSS grids

### ISSUE THREAD

**Issue by patryknawolski** [meetjspl/poznan#65]
#tables #floats #inline-blocks #flexbox #grid

How we came to Flexbox and CSS Grid? How did we layout things before? How did we create grids before? Why newer methods are better and what problems they solve? What should I use today?

And what's a grid exactly?

A quick story about what used to be and today followed by live coding with re-creating the same grid with old and modern techniques.

**Comment by erykpiast** [comment]
Dawno nikt nic nie mówił o CSSach!

**Comment by erykpiast** [comment]
Dzięki za prezentację! Wrzucisz slajdy? :)

**Comment by patryknawolski** [comment]
Proszę bardzo @erykpiast https://drive.google.com/file/d/1YHcC0L-ErGMG3Ql5cVdEovxc6EoZYxZA

**Comment by erykpiast** [comment]
Cudownie! Bardzo fajna prezentacja, przydało się takie przypomnienie. Czekamy na kontynuację o CSS Grid :)
