### ISSUE TITLE
Koniec CSS? Jest Tailwind!

### ISSUE THREAD

**Issue by amakoz** [meetjspl/poznan#66]
Prezentacja o Tailwind CSS i jak przy jego pomocy tworzyć Frontend. Prowadziłem już podobną prelekcję na meetupie Backendowym, który organizuje firma w której pracuję. Ze zdjęcia poniżej widać popularność tego narzędzia w świecie Frontendu, a w mojej opinii warto to zmienić. 

![image](https://user-images.githubusercontent.com/13831666/56885239-4188b000-6a6c-11e9-8a1e-8acadfbcc552.png)

https://tailwindcss.com/docs/what-is-tailwind

**Comment by erykpiast** [comment]
Brzmi ciekawie. Chciałbym zobaczyć porównanie rozmiarów kodu źródłowego i wynikowego dla tej samej strony napisanej w Tailwind / Bootstrapie / Vanilla CSS. Wyobrażam sobie, że to ogrom pracy, ale może autorzy projektu dysponują takim przykładem?

**Comment by amakoz** [comment]
> Brzmi ciekawie. Chciałbym zobaczyć porównanie rozmiarów kodu źródłowego i wynikowego dla tej samej strony napisanej w Tailwind / Bootstrapie / Vanilla CSS. Wyobrażam sobie, że to ogrom pracy, ale może autorzy projektu dysponują takim przykładem?

Postaram się coś przygotować

**Comment by erykpiast** [comment]
Czy chciałbyś przedstawić temat na najbliższym evencie, 21 maja?

**Comment by erykpiast** [comment]
@amakoz ping :)

**Comment by amakoz** [comment]
Sorry za brak odpowiedzi ale wyjeżdżam na urlop i mam troche na głowie. Z tego też powodu nie bede w stanie 21go przedstawić tematu. Dziś wyszła wersja 1.0 wprowadzająca dużo zmian więc na czerwiec myślę że przygotuje się lepiej z przedstawieniem podstaw i nowości.

**Comment by erykpiast** [comment]
Pewnie, dzięki za odpowiedź! Przypomnę się bliżej czerwcowego spotkania. Udanego wypoczynku! :)

**Comment by erykpiast** [comment]
@amakoz czy pasuje Ci 24 czerwca?

**Comment by amakoz** [comment]
@erykpiast pasuje :)

**Comment by erykpiast** [comment]
@amakoz a 25.06? (wtorek) Coś mi nie wyszło z obsługą kalendarza :)

**Comment by amakoz** [comment]
Uuu tu niestety nie dam rady :/

**Comment by erykpiast** [comment]
Spoko, rozumiem! Następnym razem :)

**Comment by erykpiast** [comment]
@amakoz czy temat jest z Twojej strony aktualny?

**Comment by amakoz** [comment]
@erykpiast  jest jakis termin ustalony? Ogolnie temat aktualny :)

**Comment by erykpiast** [comment]
Świetnie! Najbliższe spotkanie planujemy 21 listopada. Wyrobisz się?

**Comment by erykpiast** [comment]
@amakoz ping!

**Comment by amakoz** [comment]
Niestety, ten termin mi nie pasuje. Sorry za pozna odpowiedz.

**Comment by erykpiast** [comment]
W porządku, dzięki za informację. Damy radę!

**Comment by erykpiast** [comment]
W porządku, dzięki za informację. Damy radę!

**Comment by erykpiast** [comment]
@amakoz ! Czy 16 stycznia Ci pasuje? :)

**Comment by erykpiast** [comment]
ping @amako

**Comment by erykpiast** [comment]
@amakoz jesteś nadal zainteresowany przedstawieniem tematu? na przykład na początku marca?

**Comment by erykpiast** [comment]
@amakoz Na razie zamykam issue, jeżeli będziesz chciał przedstawić temat, daj znać.
