### ISSUE TITLE
Perfect working environment in 5 days

### ISSUE THREAD

**Issue by bigsergey** [meetjspl/poznan#67]
## Opis

Chcę opowiedzieć o narzędziach, których używam w codziennej pracy. 
Będę mówił o:
* linterach
* formaterach kodu
* precommit/postcommit hookach
* narzędziach do testów
* edytortach i IDE
* terminalu
* ...

## Forma

Prezentacja ze slajdami i gifami (nie chcę live coding'u)

P.S. Sorry za prawie puste issue, przypadkiem kliknąłem.

**Comment by bigsergey** [comment]
https://slides.com/sergeybolshov/deck-6

**Comment by erykpiast** [comment]
Dzięki @bigsergey za super prezentację! 📼 https://www.youtube.com/watch?v=_JRf_3rwkX4
