### ISSUE TITLE
Node.js parallel processing

### ISSUE THREAD

**Issue by kononenko-a-m** [meetjspl/poznan#68]
Till now Node.js was treated as solution which can only route computation to some third-parties (DBs, services implemented in other technologies), right now it's not an issue anymore. Threads was in Node.js for long time, but right now it's be used for custom CPU intensive computations without need for creating native module.

**Comment by SebastianPozoga** [comment]
Są już nagrania
https://www.youtube.com/watch?v=5lPqcTtyc24

**Comment by erykpiast** [comment]
@kononenko-a-m prawie bym zapomniał: dorzucisz slajdy?

**Comment by kononenko-a-m** [comment]
[Node.js and parallel processing.pdf](https://github.com/meetjspl/poznan/files/3717593/Node.js.and.parallel.processing.pdf)
@erykpiast są w tym PDFie
