### ISSUE TITLE
Switch from pull to push-based approach with RxJS

### ISSUE THREAD

**Issue by wojtrawi** [meetjspl/poznan#69]
I will briefly introduce you to the concept of reactive programming and present main building blocks of the RxJS library. During the presentation you will learn how to start thinking in a reactive way in order to accomplish common challenges. In addition, I will perform a sort of live coding during which I will implement a service in both pull and push-based approach. Pros and cons of the both approaches will be outlined.

**Comment by SebastianPozoga** [comment]
Są już nagrania
https://www.youtube.com/watch?v=2ifTXpMtLrw

**Comment by erykpiast** [comment]
Huh, zgapiłem się. @wojtrawi dorzucisz link do slajdów?

**Comment by wojtrawi** [comment]
jasne @erykpiast 
http://slides.com/wojtrawi/from-pull-to-push-based-approach-with-rxjs#/
