### ISSUE TITLE
Podejście reaktywne: Streams i Observables w JavaScript na obrazowych przykładach.

### ISSUE THREAD

**Issue by belfz** [meetjspl/poznan#7]
(Tytuł może ulec zmianie)

Hej,

chciałbym opowiedzieć o tym, czym w istocie jest to "mityczne" programowanie reaktywne oraz *Observables* (szczególnie chciałbym się skupić na **obrazowych przykładach**, których wg. mnie brakuje w materiałach dostępnych w sieci, a które mogą pomóc zrozumieć m.in. operacje na stream/observable). Chcę wyjaśnić kilka prostych przykładów z bibliotek [RxJS](http://reactivex.io/) i [Kefir](https://rpominov.github.io/kefir/#); pokazać (często przytaczane) porównania do Promise'ów.

Następnie chciałbym opowiedzieć o framework'u [Cycle.js](http://cycle.js.org/) - czym jest i dlaczego warto go wypróbować. Chciałbym także porównać go do React'a, a przy tym wyjaśnić kilka niejasności (m.in. dlaczego React reaktywny wcale nie jest :-) ).

Na koniec z chęcią zaprezentuję również (moją) prostą [appkę napisaną przy użyciu Cycle](https://github.com/belfz/cyclejs-mkdown-editor-app). 

Liczę na to, że z początkiem 2016r. pojawi się możliwość prezentacji na poznańskim meet.js :)

**Comment by erykpiast** [comment]
:+1: jeżeli byś potrzebował wsparcia, chętnie pomogę, contributowałem swego czasu do cycle-core. kiedy jeszcze nikt o tym nie słyszał :D

**Comment by belfz** [comment]
Super, mam nadzieję, że temat zostanie dobrze przyjęty :)

Póki co nie mam jeszcze gotowej prezentacji, ale zamierzam ją zrobić mniej więcej do lutego. Przed wystąpieniem oczywiście udostępnię tutaj prezentację licząc na feedback :)

**Comment by naugtur** [comment]
Bardzo wartościowy temat.
Jedyne co mnie martwi to że chcesz bardzo dużo zmieścić w jednej prezentacji. Z Twojego opisu widzę, że masz materiał na co najmniej dwie. 

Prelekcje mają po 20-25 minut. Szkoda by było przelecieć szybko po observable i zgubić połowę widowni.

Gdybyś przekonująco i na realnych przykładach wyjaśnił observable i do czego je stosować w 20 minutowej prezentacji, miałbyś mój głos na najlepszą prelekcję 2016, mimo że nie wiem co będzie dalej :)

Pomyśl czy nie wolałbyś zrobić z tego zestawu prelekcja 20 minut dla 100 osób + warsztaty z zapisami na 10-30 osób (ile uznasz za stosowne) z realnymi przykładami i cycle.js

**Comment by rpCal** [comment]
super pomysł, bardzo ciekawy temat.

**Comment by belfz** [comment]
@naugtur masz rację. Postaram się skupić jednak na Rx/Kefir i Observable'ach.
A potem chętnie wystąpiłbym drugi raz z częścią związaną z frameworkami (lub w formie warsztatów). Dlatego tytuł niedługo zmienię. :)

**Comment by naugtur** [comment]
podlinkuj prezentację i zamykam

**Comment by SebastianPozoga** [comment]
Prezentacja dostępna na:
http://events.pozoga.eu/meet-js-marzec-2016/
