### ISSUE TITLE
TypeScript: dzieła zebrane

### ISSUE THREAD

**Issue by przemyslawjanpietrzak** [meetjspl/poznan#70]
Postaram się podczas prezentacji opowiedzieć o mniej znanych funkcjach tego języka.

Zacznę od sztuczek ułatwiających migrację JS->TS, opowiem o ustawieniach kompilatora i co można za ich pomocą uzyskać. Później wyjaśnię takie mechanizmy jak union/merge/unknown/never. A w ostatnim akcie przedstawię jak można manipulować interfejsami.

Prezka wymaga podstawowej znajomości TypeScripta.

**Comment by erykpiast** [comment]
Przemysławie! Czy połowa października Ci pasuje?

**Comment by przemyslawjanpietrzak** [comment]
Pasuje

**Comment by przemyslawjanpietrzak** [comment]
Slajdy: https://github.com/przemyslawjanpietrzak/przemyslawjanpietrzak.github.io/blob/master/ts/presentation.pdf

**Comment by erykpiast** [comment]
Dziękuję za fascynującą prezentację, Przemysławie!
