### ISSUE TITLE
A year of Reason

### ISSUE THREAD

**Issue by pewniak747** [meetjspl/poznan#71]
[Reason-React](https://reasonml.github.io/reason-react/) to biblioteka pozwalająca na pisanie aplikacji frontendowych z użyciem React.js i nowego, statycznie typowanego języka programowania - [Reason](https://reasonml.github.io/).

Chciałbym opowiedzieć o moich doświadczeniach z tą technologią w dużym projekcie produkcyjnym. Używamy Reasona od 1.5 roku, stąd też tytuł :).

**Agenda**

Planuję skupić się na:
* Krótkim opisie kontekstu: m.in. stacka technologicznego i architektury aplikacji (Reason, Reason-React, OCaml).
* Wadach i zaletach Reasona, głównie tych nieoczywistych, wynikających ze skali i długości projektu.
* Opinii na temat opłacalności adopcji tej technologii w innych projektach.

**Motywacja**

Wiele było już prezentacji wprowadzających do Reason (w tym na meetjs poznań by @sharnik (https://www.youtube.com/watch?v=1qvUPydIsLs) oraz na meetjs summit 2018 by Bartosz Król (https://www.youtube.com/watch?v=aIJ1z53_9cw).

Myślę więc że moja prezentacja byłaby ciekawa dla społeczności meet.js - pokazałaby konkretne, poparte doświadczeniem trade-offy tej technologii. Po prezentacji, osoby zainteresowanie adopcją Reasona w istniejących lub nowych projektach będą mogły podjąć  decyzję mając pełniejszy obraz sytuacji. A dla osób które nie planują inwestować w Reason, będzie to poszerzenie horyzontów na temat innej technologii, które ciężko uzyskać z wprowadzających materiałów (które skupiają się raczej na zaletach).

**Termin**

Najbardziej pasowałby mi okres powakacyjny - koniec września, październik.

**Comment by virzen** [comment]
Yes!

**Comment by erykpiast** [comment]
Sam koduję w Reasonie od jakiegoś czasu, (ale side-project, tak bardziej *rozsądnie* 😉 😉), z chęcią posłucham!

Czy ewentualnie połowa października jest dla Ciebie realnym terminem na prezentację? @pewniak747

**Comment by pewniak747** [comment]
@erykpiast 

> Czy ewentualnie połowa października jest dla Ciebie realnym terminem na prezentację?

Myślę że tak.

> Sam koduję w Reasonie od jakiegoś czasu (ale side-project [...])

Świetnie 😃 Jakbyś miał jakieś pytania odnośnie użycia Reasona w większym projekcie to napisz, może odpowiem w prezentacji.

**Comment by erykpiast** [comment]
Największy problem, na który natrafiłem do tej pory, to formatowanie OCamla w edytorze. Ale to moja wina, uparłem się mieć rzeczy bez JSX-a w `.ml` :) Trzeba było zostać przy jednej składni.

Zdaje się, że mamy już komplet na najbliższy meetup, czy 21 listopada jest dla Ciebie dogodnym terminem?

**Comment by pewniak747** [comment]
>  czy 21 listopada jest dla Ciebie dogodnym terminem?

@erykpiast Nie masz na myśli 21 października? Jakby co pasuje mi zarówno 21 pazdziernika jak i 21 listopada 👍

**Comment by erykpiast** [comment]
Listopad :) Na październik mamy już jednego prelegenta od sponsora i osobę, która głosiła prezentację wcześniej. Nie martw się, zleci szybko! :D

**Comment by erykpiast** [comment]
@pewniak747 jeszcze raz się upewnię (😉 😉), 21 listopada prezentujesz?

**Comment by pewniak747** [comment]
> 21 listopada prezentujesz?

@erykpiast Tak, potwierdzam 👍

**Comment by erykpiast** [comment]
@pewniak747 wielkie dzięki za prezentację! Podrzucam link do nagrania: https://youtu.be/LFjUMa5LFok

Dodasz slajdy?

**Comment by pewniak747** [comment]
Jasne, oto slajdy w PDF: [A year of Reason.pdf](https://github.com/meetjspl/poznan/files/3888093/A.year.of.Reason.pdf)
