### ISSUE TITLE
Jenkins CLI

### ISSUE THREAD

**Issue by Bielik20** [meetjspl/poznan#72]
CLI based Jenkins invoker powered by RxJs.

Tool is used in our team to:
- start and track Jenkins job
- chain multiple jobs 
  - run them in parallel and sequentially

To make it work we also created
- **Jenkins RxJs** which allows to invoke Jenkins job and listen for a stream of observables describing current status of the job.
- **Jenkins Jobs Runner** is a library powered by Jenkins RxJs that enables sequential execution of `n` batches, each of `m` parallel jobs. On top of that, it provides a console visual interface to display the current status of jobs.

Presentation will go through those libraries - code is open source.

**Comment by erykpiast** [comment]
Dobrze byłoby porównać to narzędzie innymi klientami, np. [Nestorem](https://github.com/cliffano/nestor) (nawet jeśli się skupić bardziej na budowie niż na opisie z perspektywy użytkownika). Rozumiem, że mieliście jakiś specyficzny problem, z którym obecne rozwiązania nie radziły sobie idealnie?

**Comment by Bielik20** [comment]
Tak, narzędzie było stworzone żeby rozwiązać problem bardzo niewygodnego
workflow testowania oprogramowania. Na samej prezentacji wspomnę o
problemie który adresowaliśmy. Jeśli chodzi o porównanie to Nestor jest
bardziej pełnoprawnym managerem Jenkinsa z konsoli. Nasze rozwiązanie
natomiast skupia się na jednym zadaniu. Myślę, że może to być dobry temat
do dyskusji, jestem ciekaw opinii innych co o tym sądzą.

W dniu pon., 30.09.2019 o 22:51 Eryk Napierała <notifications@github.com>
napisał(a):

**Comment by erykpiast** [comment]
Dzięki za prezentację @Bielik20! Wrzucisz slajdy? :)

**Comment by Bielik20** [comment]
Jasne :D

- [Slajdy](https://docs.google.com/presentation/d/1D0Gi6-2RbMkxU1QOjLjtlF4ObvBygyYHQ1JYKLoVicA/edit?usp=sharing)
- [Artykuł](https://medium.com/fandom-engineering/jenkins-cli-4dfcee951e2a)
- [jenkins-rxjs](https://www.npmjs.com/package/jenkins-rxjs)
- [jenkins-job-runner](https://www.npmjs.com/package/jenkins-jobs-runner)
