### ISSUE TITLE
Improving mobile web performance

### ISSUE THREAD

**Issue by nandy-andy** [meetjspl/poznan#73]
#talkidea

In 2017 we improved performance of our mobile web application. The presentation can remind why it's worth to think about web performance and a good discussion starter could be: if and why it's hard to think about it in everyday work? :-)

I had data from real-life use-case gathered since half of 2018. Wanted to present it with a friend but he has different priorities in life :-) Some additional audits have been done this year and I tried to gather everything I recall in the concept below.

## Concept
1. A small time travel to 2007 and the golden rule of web performance
2. Fast-forward to 2017 and results from our AMP experiment
  a) what's AMP?
  b) what was our experiment and its results?
3. Different performance metrics
  a) page size,
  b) page load time,
  c) number of requests,
  d) number of images,
  f) time to last byte,
  e) time to start render,
  g) time to first meaningful render,
  h) time to interactive,
  i) time to visually complete,
  j) first contentful paint.
4. Things we changed
  a) loaded assets from the same domain,
  b) add pre-connect and dns-fetch attributes,
  c) create and share guidelines on ad products,
  e) removed legacy code and tech debt (jQuery, unnecessary requests, call for some assets earlier, ads),
  f) added Bortli compress protocol.
5. Tools we used
  a) WebPageTest,
  b) Google Lighthouse,
  c) Chrome UX reports in BigQuery,
  d) our internal solution and proxy for time to visually complete.
6. Learnings and open questions
  a) should we really care?
  b) how to approach it correctly?
  c) why is it hard?

## Doubts
The lists above seem long and it's easy to make the presentation long and boring. Also, is meetjs the right place to talk about it? Many of the points above aren't relevant to most of the work front-end developers do nowadays which is connected more with single page applications. With single page applications performance is still important but we focus on a different aspects, I believe (more like on [perceived performance](https://www.smashingmagazine.com/2015/09/why-performance-matters-the-perception-of-time/)).

Any feedback and advices how to go with it are more than welcome :-)

**Comment by erykpiast** [comment]
I think it's a very important topic, especially for front-end developers, as there is usually no one else in the team to care about those things or even pay the attention to. Go on!

The most interesting aspect for me is how those improvements in perceived performance have affected users' behavior and how was their eventual impact on business metrics.

**Comment by nandy-andy** [comment]
Gotcha! Definitely such view will be valuable. I'll need to retrospectively dig a little bit more to see if I can get something like that from the 2017 project ;-)

I have also a plan B which is a story from quite recent task when we removed just one client-server-client round of communication and noticed a business impact - I'll bring that if I'm not able to find anything useful from 2017 :-)

In terms of time and readiness -- I doubt I'll be able to present anything in November but I'm aiming to finish slides in November and let you know 👌

**Comment by erykpiast** [comment]
@nandy-andy would you like to give a speech at 16th of January?

**Comment by nandy-andy** [comment]
@erykpiast I won't be in Poland, unfortunately :-( If you somehow move the event to the next week it's possible. If you can't move the event let's talk about February. I've started putting slides together ;-)

**Comment by erykpiast** [comment]
In February we'll have a meeting on the 20th. Does it fit you?

**Comment by nandy-andy** [comment]
Yes! Let's do this 🚀

**Comment by erykpiast** [comment]
Hey @nandy-andy! We moved the event to 12th of March. Is that OK date for you?

**Comment by nandy-andy** [comment]
I was expecting a different date when reading comments in https://github.com/meetjspl/poznan/issues/80 But damn! I was hoping first week of March 🤞 

I won't be in Poznań between 9th and 13th March :-( Do you think you can move the event one week earlier or later? If not, then I'm afraid we need to find a replacement for me.

From a more positive side: do you want to review the slides earlier? I think next week I can share it with you via e-mail or something ;-)

**Comment by erykpiast** [comment]
Huh, that's bad news indeed! But I understand it, no worries. The next event is expected to happen on the 28th of April. Save the date :)

We don't require slides to review, but if you wish to get some feedback, feel free to attach them here or send it to poznan@meetjs.pl! :)

**Comment by nandy-andy** [comment]
I think we can close it as "old and forgotten" 😊 

The world has changed and I saw couple other ideas about web vitals here. More accurate, more up-to-date 👍 

Sorry for inconvenience! See you at #50 meet.js Poznań :)
