### ISSUE TITLE
Apps in Ads

### ISSUE THREAD

**Issue by jacekbj** [meetjspl/poznan#74]
At Fandom we built a setup to develop custom "apps" (think: micro frontends) to multiple platforms we support. Apps are delivered in an unconventional way: through an ad server. We use the apps to run UX experiments centered around ad layouts and forms.

Talk plan:
I will start with explaining how ad stack works (in a very simplified way to establish common ground).
Then I will proceed to outline how to deliver custom code through the ad server. I will say a few words about communication between micro frontends and how we iterate fast with the use of end to end tests.

I want the talk to be at basic level so that a wide audience can enjoy it.

**Comment by erykpiast** [comment]
Sounds more than interesting!

**Comment by jacekbj** [comment]
Perfect! I have slides almost ready so I don't need much time to prepare.

**Comment by erykpiast** [comment]
Alright! There is a little queue, so be prepared for December meeting :)

**Comment by jacekbj** [comment]
December sounds great, keep me posted.

**Comment by erykpiast** [comment]
@jacekbj there will be no meeting in December (except the Christmas Eve dinner of course). What about January? Does the 16th fit you?

**Comment by jacekbj** [comment]
Sounds great! Let me know how much time I have to polish the description.

**Comment by erykpiast** [comment]
The presentation should take 20-25 minutes :)

You can share detailed agenda here if you wish to get some early feedback. Feel free to ask for comments!

**Comment by naugtur** [comment]
To make things clear - we don't require description or agenda. You would only work on it if you want to get feedback here. 
We only require a topic upfront and a nice 20 minutes talk at the event :)

**Comment by jacekbj** [comment]
FYI I changed the topic slightly to make it more sexy: "Apps in Ads"

**Comment by erykpiast** [comment]
@jacekbj Thanks a lot for great talk! Could you share the slides?

**Comment by jacekbj** [comment]
Yes, I will try to post them over the weekend.
