### ISSUE TITLE
Bringing order to git repositories with Git Hooks, GitFlow and Husky (GitFlow, Git Hooks oraz Husky na straży porządku w repozytorium git)

### ISSUE THREAD

**Issue by jablpiotrek** [meetjspl/poznan#76]
> I've started writing this thing in polish some time ago, so it is in polish. If you don't speak it, please let me know, I'll rewrite it to english right away. 

Chciałbym w tej prezentacji przedstawić parę podstawowych koncepcji mających ułatwić i usystematyzować pracę z istniejącymi lub nowymi repozytoriami git z wykorzystaniem GitFlow, git hooków i Husky'iego. 

**Problem:** Większość projektów nad którymi przychodzi nam pracować czy to komercyjnie, czy w społeczności opensource, ma to do siebie że rzadko pracuje się w pojedynkę. Repozytorium git staje się miejscem, z którego korzysta naraz wiele osób, i jak to w takich przypadkach bywa - prędzej czy później pojawia się bałagan. Git flow i git hooki to narzędzia dzięki którym, małym nakładem czasu (pieniędzy) można ten bałagan okiełznać, a przy umiarkowanym zaangażowaniu zasobów wyeliminować w przyszłości.  Chciałbym, aby ta prezentacja dostarczyła tym, którzy o ich istnieniu nie wiedzą - narzędzi, a tym którzy te narzędzia znają - motywacji do ich stosowania. 

Plan:
1. Problemy codzienności przy kolaboracji wielu osób w jednym repozytorium git

- Dlaczego w ogóle potrzebujemy zasad pracy w repozytorium?

- Czym brak takich zasad może skutkować?

- Dlaczego pomimo szczerych chęci i zaufania, potrzebujemy technologii i narzędzi które będą pilnować porządku w repo?

2. Git Flow

- Szybki recap samej metodologii

- Jakie problemy próbuje to rozwiązać i z jakim skutkiem - w skrócie co to nam w zasadzie daje?

- Techniczne strony wykorzystania Git Flow w CLI i popularnych GUI dla git

3. Git Hooks.

- Czym są hooki w git, i co oferują?

- Jak wygląda podstawowa implementacja Git Hooków?

- "Życiowe" przykłady wykorzystania hooków w zapobieganiu częstym "niesubordynacjom" w repozytorium.

4. Husky (ale też inne rozwiązania) ułatwiające implementację git hooków.

- Podstawowe informacje o sposobach implementacji.

- Przykłady, przykłady.

5. Dyskusja - przykładowe "starting points".

- Gdzie kończy się rozsądna organizacja repozytorium a zaczyna ograniczanie wydajności i komfortu pracy poprzez narzucanie nierozsądnych wymagań?

- A czy to działa w zdalnym repo? Jak to jest z hookami na serwerze?

- Kiedy naprawdę warto pomyśleć o sformalizowaniu wymogów dla commitów trafiających do naszego repo? Czy to tylko kwestia wielkości repozytorium i ilości "kontrybutorów"?

**Dla kogo ta prezentacja?:**
Nie ma co ukrywać - przede wszystkim dla mnie. Uczestniczę w poznańskich meetupach jako słuchacz od jakiegoś czasu i czuję że mógłbym i bardzo chciałbym przyłożyć się do tego od tej bardziej aktywnej strony, ale też sprawdzić się przed większą i na pewno bardziej wymagającą publicznością. A jeśli idzie o publiczność - to chciałbym żeby to wystąpienie z jednej strony dało coś ludziom zaczynającym swoją karierę (a tych, wnosząc po dyskusjach "przy piwie" na meetupach, jest całkiem spora grupa) a z drugiej strony - żeby starzy wyjadacze raz że nie posnęli w trakcie, a dwa - może włączyli się do dyskusji albo zainspirowali się jakimś, zdawałoby się oczywistym, konceptem. Jestem świadom tego jak to jest trudne, ale bardzo chciałbym żeby w trakcie prezentacji pojawił się jakiś dialog. Git jest zagadnieniem z którym pracuje praktycznie każdy, niezależnie od technologii i doświadczenia, i każdy ma coś do powiedzenia. Wierzę że dzięki temu uda się rozkręcić dyskusję jeśli nie w trakcie prezentacji, to po niej. Uważam, że mocną stroną tematu jest to że może dotyczyć każdego, nie zważając na technologię, obszar biznesowy pracy, doświadczenie czy rolę w zespole. 

**Organizacyjnie:** 
Nie wiem jak wyglądają plany na wystąpienia przed końcem roku. Do końca listopada nie ma mnie w Polsce, w grudniu planuję mieć wyjątkowo dużo czasu wolnego więc mógłbym coś przygotować  i zaprezentować  - plan jest w głowie, wypadałoby go przelać na jakieś mnie ulotne medium. Zakładając że temat zostałby uznany za ciekawy (lub, minimalnie haniebny dla dotychczasowego poziomu meetupu), chętnie przygotuję i przedstawię go przed końcem roku lub na początku nadchodzącego. Mogę to zrobić w języku polskim lub angielskim - nie robi mi to żadnej różnicy (ten issue jest po polsku, ale jeśli jest potrzeba przepiszę to na język Szekspira).

**Comment by erykpiast** [comment]
@jablpiotrek Ważny temat! Przy tym to chyba najbardziej rozbudowany abstrakt, jaki widziałem do tej pory w tym repozytorium, nie wiem nawet, co mógłbym zasugerować :)

Umówmy się wstępnie na początek przyszłego roku, powiedzmy, na połowę stycznia. Może tak być?

**Comment by jablpiotrek** [comment]
@erykpiast oczywiście, pasuje mi to.
Abstrakt rozbudowany bo i powstawał na raty przez kilka miesięcy XD

**Comment by naugtur** [comment]
Cześć! Zawsze się cieszę widząc że ktoś odkrywa w sobie chęć dzielenia się wiedzą.

Kilka podpowiedzi.

W sekcji 1 uważaj żeby nie wałkować oczywistości tylko fajnie zaznaczyć problem. Np krótką historyjka albo ironicznym memem.

Oryginalny git flow jest trochę rozbudowany. Warto poświęcić czas na zaznaczenie do czego są potrzebne te działania i kiedy są ważne a kiedy nie robią większej różnicy

**Comment by jablpiotrek** [comment]
@naugtur dzięki!

**Comment by erykpiast** [comment]
@jablpiotrek czy pasuje Ci, żeby przedstawić temat 16 stycznia?

**Comment by jablpiotrek** [comment]
@erykpiast no pewnie że pasuje!

**Comment by erykpiast** [comment]
Super! Wpisuję do agendy :)

**Comment by erykpiast** [comment]
@jablpiotrek Wielkie dzięki za prezentację! Wrzucisz tu slajdy?

**Comment by jablpiotrek** [comment]
@erykpiast @naugtur ja również dziękuję!
[meetjs47.pdf](https://github.com/meetjspl/poznan/files/4097309/meetjs47.pdf)

Ja proszę o zdjęcia :)
