### ISSUE TITLE
Lightning workshop: wyciek pamięci

### ISSUE THREAD

**Issue by naugtur** [meetjspl/poznan#79]
Mikro warsztat pokazujący jak zabrać się za zidentyfikowanie wycieku pamięci.

10-15 minut

Uczestnicy mogą pracować na swoich laptopach lub tylko obserwować.

**Comment by erykpiast** [comment]
Będzie dostępne jakieś repo do sklonowania? Można by to wrzucić do agendy spotkania. W razie gdyby na miejscu internet zawiódł :)

**Comment by naugtur** [comment]
Robi sens. Mam jedno gotowe ale chciałem zrobić prostsze

**Comment by naugtur** [comment]
Done.
