### ISSUE TITLE
Datascript, Datalog w przeglądarce.

### ISSUE THREAD

**Issue by adrianmroz** [meetjspl/poznan#8]
Chciałbym opowiedzieć o bibliotece [datascript](https://github.com/tonsky/datascript). O podstawowej formie danych w tej bazie, o języku zapytań i dlaczego pasuje on do dzisiejszych praktyk tworzenia aplikacji (pull api, append only log, immutable).

**Comment by naugtur** [comment]
Dobre.  Przydałyby się przykłady użycia, żeby wiedzieć do czego to ;)
Porównanie do `indexedDB` też się przyda (wiem, że to zupełnie różne rzeczy, ale warto o tym powiedzieć)

**Comment by adrianmroz** [comment]
Jeśli już porównywać to bardziej myślałem o PouchDB/CouchDB. Obgadamy, jak będę miał outline!

**Comment by adrianmroz** [comment]
spoilers alert

http://slides.com/dhucerbin/datascript#/

**Comment by naugtur** [comment]
slajdy są, zamykam.

**Comment by SebastianPozoga** [comment]
Prezentacja dostępna na:
http://events.pozoga.eu/meet-js-poznan-czerwiec-2016/
