### ISSUE TITLE
Context API - czy może zastąpić Reduxa?

### ISSUE THREAD

**Issue by iiskaandar** [meetjspl/poznan#84]
Zaczynając pracę nad nowym projektem Reactowym przychodzi moment, gdy musimy zastanowić się jak zarządzać stanem aplikacji między komponentami. W pierwszej kolejności przychodzi nam do głowy Redux, który często dodawany jest do projektu bez głębszego zastanawiania "Czy na pewno jest nam potrzebny?".

Context API to wbudowana funkcjonalność Reacta umożliwiająca komponentom przekazywanie danych do innych komponentów. Czy możemy zarządzać stanem aplikacji wyłącznie przy pomocy Context API? Jakie niesie to za sobą konsekwencje? Co się stanie z performancem naszej aplikacji? W jaki sposób debuggować stan? Na te pytania odpowiem w mojej prezentacji.

**Comment by naugtur** [comment]
Super! Dzięki za zgłoszenie. 

Wystarczy miejsca w prezentacji żeby zestawić to podejście z użyciem valtio, ewentualnie zustand?

**Comment by iiskaandar** [comment]
Świetna propozycja! I postaram się to dodać. Na pewno pokażę w jaki sposób ulepszyć Context API (przy pomocy xState), kiedy projekt zaczyna robić się za duży.

**Comment by naugtur** [comment]
To może dodamy xstate i jakieś jeszcze buzzwordy do tytułu żeby przyciągnąć więcej ludzi? 😅

**Comment by tiriana** [comment]
A kiedy będzie ten talk?

**Comment by naugtur** [comment]
https://www.meetup.com/meet-js-Pozna%C5%84/events/280614182/ 23 września. Wbijaj

**Comment by naugtur** [comment]
zrealizowane
