### ISSUE TITLE
Czy warto się uczyć Vue w 2022* roku i dlaczego nie?

### ISSUE THREAD

**Issue by przemyslawjanpietrzak** [meetjspl/poznan#85]
Po ponad roku z vue chciałbym nieco bardziej go Wam przybliżyć, ale nie w formie kolejnego wstępu do frameworka, tylko pokazać różnice w pracy z nim, reactem i angularem. Przedstawić parę przykładów w których vue zaskakuje (na plus i na minus). I na podstawie tego określić przesłanki kiedy może on być dobrym/złym wyborem. A w ostatniej części spróbuję odpowiedzieć kiedy inwestycja czasu w jego naukę ma szansę się zwrócić.

**Comment by naugtur** [comment]
Mocne. W Poznaniu mieszka jeden czy dwóch core contributorów do Vue i nawet bywał na meet.js-ach - może byśmy z tego zrobili jakiś panel dyskusyjny?

**Comment by przemyslawjanpietrzak** [comment]
@naugtur up to you. Nie wiem czy takie mocne. To nie ma być lincz, tylko zestawienie różnic i analiza kiedy lepiej użyć reacta, angulara, a kiedy iść we vue.

**Comment by naugtur** [comment]
Mam pozytywne wrażenia po przeczytaniu zajawki, tytuł jest z pazurem, ale to dobrze 🙂

Piszę o tym bo nie wiem czy się masz ochotę tak konfrontować.

**Comment by przemyslawjanpietrzak** [comment]
Mam pomysł na samą prezkę, ale jeżeli się uda taki vuowy panel zorganizować to jasne

**Comment by tniezurawski** [comment]
Bardzo mi się podoba ten temat. Brakuje dobrych porównań frameworków i prób odpowiedzenia na pytanie kiedy jaki wybrać.

**Comment by przemyslawjanpietrzak** [comment]
@naugtur działamy coś?

**Comment by naugtur** [comment]
Na razie spotkania IRL mało prawdopodobne :) a do wersji online brakuje załogi. Sam nie zrobię, bo mi chwilowo życie zajmuje za dużo uwagi. 
Na razie poszukam kontaktów do wspomnianych wyżej ludzi od vue, to wtedy moglibyśmy zrobić event z prezentacją a dyskusję nagrać jako podcast. 

W skrócie - jeszcze nie działamy, ale plany są :)

**Comment by cdynak** [comment]
Hej, jak coś to jestem zainteresowany wparciem tematu zarówno ze swojej strony jak i przez https://www.stxnext.com/ :) Skontaktować z nowym kolegą od event'ów z Poznania?

**Comment by orchowski** [comment]
@przemyslawjanpietrzak Gdyby meetjs odbył się 31 maja - byłbyś chętny przedstawić wtedy temat?

**Comment by przemyslawjanpietrzak** [comment]
@orchowski Chętnie :)

**Comment by orchowski** [comment]
> @orchowski Chętnie :)

Super! Póki co jeszcze organizujemy miejscówkę itd - dam znać jak już wszystko potwierdzimy.

**Comment by naugtur** [comment]
Leci ogłoszenie

**Comment by przemyslawjanpietrzak** [comment]
Slajdy:
[presentation.pdf](https://github.com/meetjspl/poznan/files/8812152/presentation.pdf)

**Comment by SebastianPozoga** [comment]
Nagranie: https://youtu.be/tMfk1dsZn8Y
