### ISSUE TITLE
Wstęp do grafiki 3D w JS

### ISSUE THREAD

**Issue by webmajstr** [meetjspl/poznan#9]
Ostatnio bawiłem się trochę z [Babylon.js](http://www.babylonjs.com/) i uważam zagadnienie za ciekawe i warte poznania. Chciałbym zrobić prezentację o tym czym jest babylon, jak rozpocząć zabawę z 3D, z jakąś wizualizacją/livecodingiem.

**Comment by naugtur** [comment]
Atrakcyjny temat. Uwaga: w sali, w której będziemy na najbliższym meet.js rzutnik ma wejście VGA i domyślnie obsługuje 1024x768. Da się wycisnąć trochę więcej na niektórych kompach.

W kontekście powiedzenia, że najlepszy livecoding jest w `.avi`, jak chcesz się do tego przygotować?
Najbliższy meet.js jest planowany na ~15 czerwca. 

Jeśli potrzebujesz coś skonsultować/podpytać to pisz.

**Comment by hzub** [comment]
@webmajstr - i udało Ci się zrobić prezentację? Tak jak @naugtur pisał, temat jest atrakcyjny i z chęcią widzielibyśmy prezentację na naszym meet.js.

**Comment by webmajstr** [comment]
Prezentację potwierdzam, ale jest jeszcze w trakcie przygotowywania. Jest jakiś deadline na przesyłanie slajdów?

**Comment by hzub** [comment]
@webmajstr: a gdybyśmy zaproponowali import prezentacji razem z Tobą - prelegentem - na wschód, czyli na białostocki meet.js? :)

**Comment by webmajstr** [comment]
Doskonała propozycja! Poczekaj jeszcze na recenzje poznaniaków :)

**Comment by hzub** [comment]
@webmajstr
Okej ;). W Poznaniu meet macie 15 czerwca?

**Comment by webmajstr** [comment]
Zgadza się

**Comment by naugtur** [comment]
wrzuć tu link do prezentacji i zamykam issue.

**Comment by hzub** [comment]
Zanim się zamknie - @webmajstr, daj proszę jakiś mailowy namiar na siebie :)

**Comment by webmajstr** [comment]
[Prezentacja](https://dl.dropboxusercontent.com/u/53484250/Wst%C4%99p%20do%20grafiki%203D.pdf). Wielkie dzięki za miłe przyjęcie, mam nadzieję że się podobało :)

**Comment by erykpiast** [comment]
Mi podobało się bardzo! Planujesz drążyć temat i ewentualnie rozwinąć go w przyszłości, czy była to taka jednorazowa przygoda? :)

**Comment by Suiseki** [comment]
Bardzo dobra prezentacja, bawiłem się trochę Blenderem więc się przyda. Przeglądam przykłady z sieci. Nie sądziłem, że tego typu biblioteki są tak wydajne.

**Comment by naugtur** [comment]
Prezentacja wrzucona, zamykam issue (ale możńa dalej gadać jakby co:) )

**Comment by webmajstr** [comment]
Dzieki za opinie. Zagadnieniem zamierzam się jeszcze trochę pobawic. Fajnie od czasu do czasu dla odmiany pobawić się trójwymiarem, z resztą pytanie o możliwość stworzenia VR przy pomocy babylona traktuję jako challenge :)

**Comment by SebastianPozoga** [comment]
Prezentacja dostępna na:
http://events.pozoga.eu/meet-js-poznan-czerwiec-2016/
