### ISSUE TITLE
EPG w Twojej aplikacji. Co to jest i jak zaimplementować?

### ISSUE THREAD

**Issue by karolkozer** [meetjspl/poznan#90]
Temat prezentacji związany z TV Online / VOD.

Agenda:
1.	Kim jestem?
a.	Krótkie wprowadzenie
b.	Czym zajmuję się zawodowo?
c.	Gdzie pracuje?
2.	Co to jest Electronic Program Guide / EPG?
a.	Opis funkcjonalności
3.	Dlaczego temat EPG?
4.	Jak wygląda EPG? Co to jest horizontal Timeline?
5.	Jakie są problemy z horizontal Timelines?
a.	Czy istnieją dobre lub złe rozwiązania?
6.	Layout – to jest Lista czy Grid?
7.	Analizy istniejących rozwiązań, podejść i wdrożeń
8.	Timeline a duża ilość danych w aplikacji / na stronie internetowej
9.	Jak zaktualizować widok interfejsu użytkownika?
10.	Pobieranie danych na każdym akcji przewijania osi Y/X?
11.	Co z szybą interakcja użytkownika z treścią EPG?
a.	Filtry, przypomnienia, kalendarze, modale z niestandardowym widokiem, ocena filmów, selekcja wybranych elementów, nagrywanie itp
12.	Planby i jego rozwiązanie
a.	Co to jest i jak działa Planby - https://planby.netlify.app
b.	Dlaczego stworzyłem Planby
c.	Lista gotowych funkcjonalności i możliwości
d.	Gotowe narzędzie do wykorzystania, przykłady

**Comment by naugtur** [comment]
Wygląda dobrze.
Jako widz chciałbym, żeby 1,2,3,7 zajęły możliwie mniej czasu a 5,6,12 jak najwięcej.

Przewidujemy 25-30 minut na prelekcję. Zmieści się, czy chcesz negocjować? :)

**Comment by karolkozer** [comment]
Hej @naugtur,
Myślę, że 25 minut jest okej.

**Comment by SebastianPozoga** [comment]
Podsyłam link do nagrania z prezentacji
https://www.youtube.com/watch?v=OH7O_Slxk_E
