### ISSUE TITLE
Inny rodzaj Server Side Renderingu. Jak użyć streamowania HTTP, aby osiągnąć maksymalną wydajność front-endu

### ISSUE THREAD

**Issue by kuba-orlik** [meetjspl/poznan#91]
Jak w tytule. W tej prezentacji zrobiłbym przegląd współczesnych metod renderowania stron i porównał je do server side renderingu połączonym ze streamingiem, aby osiągnąć minimalne możliwe TTFB

**Comment by SebastianPozoga** [comment]
Czy chciałbyś poprowadzić prezentacje 27.06??

**Comment by kuba-orlik** [comment]
Tak ❤️

**Comment by SebastianPozoga** [comment]
Jest nagranie z prezentacji :-)
https://youtu.be/qFXpDGNjc4M
