### ISSUE TITLE
The higher order of types

### ISSUE THREAD

**Issue by belfz** [meetjspl/poznan#92]
Cześć!

Z chęcią zaprezentuję swój temat pt. **The higher order of types**, który prezentowałem już raz, na meet.js w Krakowie we Wrześniu 2019, a który w mojej ocenie nadal jest aktualny :)

Wrzucam krótki abstrakt (w języku angielskim, choć prezentację poprowadzę po polsku):

_Bringing the type safety in your TypeScript projects to a whole new level. This talk shows how functional programming paradigms can help write a safer, more robust code using the "Maybe" monad. Examples included!_

**Comment by olafkrawczyk** [comment]
Hej, czysto formalnie. Czy termin 27.06 Ci odpowiada?

**Comment by belfz** [comment]
Hej, jak najbardziej :)

**Comment by SebastianPozoga** [comment]
Jest już nagranie:
https://youtu.be/XovgAfifiG0
