### ISSUE TITLE
Javascript.exe - Jak tworzyć standalone executable JavaScript apps

### ISSUE THREAD

**Issue by FranekMarciniak** [meetjspl/poznan#93]
Cześć! Ostatnio zainteresowałem się tematem bundlowania aplikacji js'owych (i nie tylko) do pojedynczych binarek. 
Temat jest dość bogaty - można podchodzić do niego na wiele sposobów, począwszy od Electrona, poprzez narzędzia third party, a kończąc na natywnym sposobie, który zadebiutuje w Node.js v20.
W trakcie prezentacji wspomnę również o podejściach w innych runtime'ach, takich jak Deno czy Bun. 
Oczywiście, uwzględnię use case'y i potencjalne problemy takiego rozwiązania.
Ze względu na dynamikę tematu, myślę że, omówienie zajmie mi 20 min plus czas na pytania :)
Dajcie znać czy taki temat się nadaje

**Comment by SebastianPozoga** [comment]
Cześć
NAstępne spotkanie planujemy 10.10.2023. Czy chcesz w tym terminie poprowadzić prezentację?

**Comment by FranekMarciniak** [comment]
@SebastianPozoga Jasne, chętnie!

**Comment by SebastianPozoga** [comment]
Dodałem stronę wydarzenia. Na początku tygodnia ruszamy z promocją. Jeśli masz jakieś uwagi / chcesz coś dodać pisz :-)
https://www.meetup.com/meet-js-poznań/events/296293629/

**Comment by SebastianPozoga** [comment]
Bardzo dziękujemy za poprowadzenie prezentacji. Niestety z uwagi na błąd przy ustawieniu wzmacniacza (problemy z dźwiękiem) nie możemy opublikować nagrań :-/ Postaram się, żeby w przyszłości nie było takich problemów.

Mam nadzieję, że Ty również wyciągnąłeś wiele z prezentacji. Nabyłeś nowe umiejętności lub dopracowałeś już posiadane. Liczymy, że będziesz z nami :-) zarówno jako uczestnik, jak i prowadzący :-)
